// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: act_samples.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct Data_PbActivityInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var value: Data_PbActivityInfo.ActivityClass {
    get {_value ?? .sleep}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  public var hasValue: Bool {self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  public mutating func clearValue() {self._value = nil}

  /// Local time is used, because the design is originally implemented in local time
  public var timeStamp: PbLocalDateTime {
    get {_timeStamp ?? PbLocalDateTime()}
    set {_timeStamp = newValue}
  }
  /// Returns true if `timeStamp` has been explicitly set.
  public var hasTimeStamp: Bool {self._timeStamp != nil}
  /// Clears the value of `timeStamp`. Subsequent reads from it will return its default value.
  public mutating func clearTimeStamp() {self._timeStamp = nil}

  public var factor: Float {
    get {_factor ?? 0}
    set {_factor = newValue}
  }
  /// Returns true if `factor` has been explicitly set.
  public var hasFactor: Bool {self._factor != nil}
  /// Clears the value of `factor`. Subsequent reads from it will return its default value.
  public mutating func clearFactor() {self._factor = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum ActivityClass: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case sleep = 1
    case sedentary = 2
    case light = 3
    case continuousModerate = 4
    case intermittentModerate = 5
    case continuousVigorous = 6
    case intermittentVigorous = 7
    case nonWear = 8

    public init() {
      self = .sleep
    }

  }

  public init() {}

  fileprivate var _value: Data_PbActivityInfo.ActivityClass? = nil
  fileprivate var _timeStamp: PbLocalDateTime? = nil
  fileprivate var _factor: Float? = nil
}

public nonisolated struct Data_PbActivitySamples: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Date and time when the sample was created for the first time
  /// Local time is used, because the design is originally implemented in local time
  public var startTime: PbLocalDateTime {
    get {_storage._startTime ?? PbLocalDateTime()}
    set {_uniqueStorage()._startTime = newValue}
  }
  /// Returns true if `startTime` has been explicitly set.
  public var hasStartTime: Bool {_storage._startTime != nil}
  /// Clears the value of `startTime`. Subsequent reads from it will return its default value.
  public mutating func clearStartTime() {_uniqueStorage()._startTime = nil}

  /// Recording interval of met samples in this file
  public var metRecordingInterval: PbDuration {
    get {_storage._metRecordingInterval ?? PbDuration()}
    set {_uniqueStorage()._metRecordingInterval = newValue}
  }
  /// Returns true if `metRecordingInterval` has been explicitly set.
  public var hasMetRecordingInterval: Bool {_storage._metRecordingInterval != nil}
  /// Clears the value of `metRecordingInterval`. Subsequent reads from it will return its default value.
  public mutating func clearMetRecordingInterval() {_uniqueStorage()._metRecordingInterval = nil}

  /// Recording interval of step samples in this file
  public var stepsRecordingInterval: PbDuration {
    get {_storage._stepsRecordingInterval ?? PbDuration()}
    set {_uniqueStorage()._stepsRecordingInterval = newValue}
  }
  /// Returns true if `stepsRecordingInterval` has been explicitly set.
  public var hasStepsRecordingInterval: Bool {_storage._stepsRecordingInterval != nil}
  /// Clears the value of `stepsRecordingInterval`. Subsequent reads from it will return its default value.
  public mutating func clearStepsRecordingInterval() {_uniqueStorage()._stepsRecordingInterval = nil}

  /// met samples
  public var metSamples: [Float] {
    get {_storage._metSamples}
    set {_uniqueStorage()._metSamples = newValue}
  }

  /// step samples
  public var stepsSamples: [UInt32] {
    get {_storage._stepsSamples}
    set {_uniqueStorage()._stepsSamples = newValue}
  }

  /// Activity class changes
  public var activityInfo: [Data_PbActivityInfo] {
    get {_storage._activityInfo}
    set {_uniqueStorage()._activityInfo = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "data"

nonisolated extension Data_PbActivityInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbActivityInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0\u{3}time_stamp\0\u{1}factor\0")

  public var isInitialized: Bool {
    if let v = self._timeStamp, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._value) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._timeStamp) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self._factor) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._value {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._timeStamp {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._factor {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbActivityInfo, rhs: Data_PbActivityInfo) -> Bool {
    if lhs._value != rhs._value {return false}
    if lhs._timeStamp != rhs._timeStamp {return false}
    if lhs._factor != rhs._factor {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Data_PbActivityInfo.ActivityClass: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}SLEEP\0\u{1}SEDENTARY\0\u{1}LIGHT\0\u{1}CONTINUOUS_MODERATE\0\u{1}INTERMITTENT_MODERATE\0\u{1}CONTINUOUS_VIGOROUS\0\u{1}INTERMITTENT_VIGOROUS\0\u{1}NON_WEAR\0")
}

nonisolated extension Data_PbActivitySamples: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbActivitySamples"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}start_time\0\u{3}met_recording_interval\0\u{3}steps_recording_interval\0\u{3}met_samples\0\u{3}steps_samples\0\u{4}\u{2}activity_info\0")

  fileprivate class _StorageClass {
    var _startTime: PbLocalDateTime? = nil
    var _metRecordingInterval: PbDuration? = nil
    var _stepsRecordingInterval: PbDuration? = nil
    var _metSamples: [Float] = []
    var _stepsSamples: [UInt32] = []
    var _activityInfo: [Data_PbActivityInfo] = []

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _startTime = source._startTime
      _metRecordingInterval = source._metRecordingInterval
      _stepsRecordingInterval = source._stepsRecordingInterval
      _metSamples = source._metSamples
      _stepsSamples = source._stepsSamples
      _activityInfo = source._activityInfo
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public var isInitialized: Bool {
    return withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._startTime == nil {return false}
      if _storage._metRecordingInterval == nil {return false}
      if _storage._stepsRecordingInterval == nil {return false}
      if let v = _storage._startTime, !v.isInitialized {return false}
      if !SwiftProtobuf.Internal.areAllInitialized(_storage._activityInfo) {return false}
      return true
    }
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._startTime) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._metRecordingInterval) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._stepsRecordingInterval) }()
        case 4: try { try decoder.decodeRepeatedFloatField(value: &_storage._metSamples) }()
        case 5: try { try decoder.decodeRepeatedUInt32Field(value: &_storage._stepsSamples) }()
        case 7: try { try decoder.decodeRepeatedMessageField(value: &_storage._activityInfo) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._startTime {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._metRecordingInterval {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._stepsRecordingInterval {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      if !_storage._metSamples.isEmpty {
        try visitor.visitRepeatedFloatField(value: _storage._metSamples, fieldNumber: 4)
      }
      if !_storage._stepsSamples.isEmpty {
        try visitor.visitPackedUInt32Field(value: _storage._stepsSamples, fieldNumber: 5)
      }
      if !_storage._activityInfo.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._activityInfo, fieldNumber: 7)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbActivitySamples, rhs: Data_PbActivitySamples) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._startTime != rhs_storage._startTime {return false}
        if _storage._metRecordingInterval != rhs_storage._metRecordingInterval {return false}
        if _storage._stepsRecordingInterval != rhs_storage._stepsRecordingInterval {return false}
        if _storage._metSamples != rhs_storage._metSamples {return false}
        if _storage._stepsSamples != rhs_storage._stepsSamples {return false}
        if _storage._activityInfo != rhs_storage._activityInfo {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
