// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: automatic_samples.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// AUTOS%03d.BPB=PbAutomaticSampleSessions

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Data_PbMeasTriggerType: Int, SwiftProtobuf.Enum, Swift.CaseIterable {

  ///Automatic measurement triggered by user high activity. Contains 1-n samples
  case triggerTypeHighActivity = 1

  ///Automatic measurement triggered by user low activity. Contains 1-n samples
  case triggerTypeLowActivity = 2

  ///Automatic measurement triggered by timer. Contains 1 sample
  case triggerTypeTimed = 3

  ///Manual measurement (other than exercise) triggered by user. Contains 1-n samples
  case triggerTypeManual = 4

  public init() {
    self = .triggerTypeHighActivity
  }

}

///
///Automatic sample session per day
public nonisolated struct Data_PbAutomaticSampleSessions: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Date of samples (starting time of 00:00 in user local time zone)
  public var day: PbDate {
    get {_day ?? PbDate()}
    set {_day = newValue}
  }
  /// Returns true if `day` has been explicitly set.
  public var hasDay: Bool {self._day != nil}
  /// Clears the value of `day`. Subsequent reads from it will return its default value.
  public mutating func clearDay() {self._day = nil}

  /// Heart rate samples
  public var samples: [Data_PbAutomaticHeartRateSamples] = []

  /// PP interval samples
  public var ppiSamples: [Data_PbPpIntervalAutoSamples] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _day: PbDate? = nil
}

public nonisolated struct Data_PbAutomaticHeartRateSamples: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// recording trigger type
  public var triggerType: Data_PbMeasTriggerType {
    get {_triggerType ?? .triggerTypeHighActivity}
    set {_triggerType = newValue}
  }
  /// Returns true if `triggerType` has been explicitly set.
  public var hasTriggerType: Bool {self._triggerType != nil}
  /// Clears the value of `triggerType`. Subsequent reads from it will return its default value.
  public mutating func clearTriggerType() {self._triggerType = nil}

  /// recording time. Delta from parent messages 'day'-field 00:00 time.
  public var time: PbTime {
    get {_time ?? PbTime()}
    set {_time = newValue}
  }
  /// Returns true if `time` has been explicitly set.
  public var hasTime: Bool {self._time != nil}
  /// Clears the value of `time`. Subsequent reads from it will return its default value.
  public mutating func clearTime() {self._time = nil}

  /// heart rate
  /// range [0 - 250] (1/min)
  public var heartRate: [UInt32] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _triggerType: Data_PbMeasTriggerType? = nil
  fileprivate var _time: PbTime? = nil
}

///
///Optical PP interval samples
///- PP interval: time period between two optical heart rate pulses
public nonisolated struct Data_PbPpIntervalAutoSamples: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Recording trigger type
  public var triggerType: Data_PbPpIntervalAutoSamples.PbPpIntervalRecordingTriggerType {
    get {_triggerType ?? .ppiTriggerTypeUndefined}
    set {_triggerType = newValue}
  }
  /// Returns true if `triggerType` has been explicitly set.
  public var hasTriggerType: Bool {self._triggerType != nil}
  /// Clears the value of `triggerType`. Subsequent reads from it will return its default value.
  public mutating func clearTriggerType() {self._triggerType = nil}

  /// Recording time, start time of the first PP interval in this sample packet
  ///   - Delta from parent messages 'day'-field 00:00 time in user local time zone
  public var recordingTime: PbTime {
    get {_recordingTime ?? PbTime()}
    set {_recordingTime = newValue}
  }
  /// Returns true if `recordingTime` has been explicitly set.
  public var hasRecordingTime: Bool {self._recordingTime != nil}
  /// Clears the value of `recordingTime`. Subsequent reads from it will return its default value.
  public mutating func clearRecordingTime() {self._recordingTime = nil}

  /// PP interval samples
  public var ppi: Data_PbPpIntervalSamples {
    get {_ppi ?? Data_PbPpIntervalSamples()}
    set {_ppi = newValue}
  }
  /// Returns true if `ppi` has been explicitly set.
  public var hasPpi: Bool {self._ppi != nil}
  /// Clears the value of `ppi`. Subsequent reads from it will return its default value.
  public mutating func clearPpi() {self._ppi = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// PP interval recording trigger types
  public nonisolated enum PbPpIntervalRecordingTriggerType: Int, SwiftProtobuf.Enum, Swift.CaseIterable {

    /// Undefined
    case ppiTriggerTypeUndefined = 0

    /// Automatic recording (for example 24/7 recording)
    case ppiTriggerTypeAutomatic = 1

    /// Manual recording (started by user)
    case ppiTriggerTypeManual = 2

    public init() {
      self = .ppiTriggerTypeUndefined
    }

  }

  public init() {}

  fileprivate var _triggerType: Data_PbPpIntervalAutoSamples.PbPpIntervalRecordingTriggerType? = nil
  fileprivate var _recordingTime: PbTime? = nil
  fileprivate var _ppi: Data_PbPpIntervalSamples? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "data"

nonisolated extension Data_PbMeasTriggerType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}TRIGGER_TYPE_HIGH_ACTIVITY\0\u{1}TRIGGER_TYPE_LOW_ACTIVITY\0\u{1}TRIGGER_TYPE_TIMED\0\u{1}TRIGGER_TYPE_MANUAL\0")
}

nonisolated extension Data_PbAutomaticSampleSessions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbAutomaticSampleSessions"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}day\0\u{1}samples\0\u{3}ppi_samples\0")

  public var isInitialized: Bool {
    if self._day == nil {return false}
    if let v = self._day, !v.isInitialized {return false}
    if !SwiftProtobuf.Internal.areAllInitialized(self.samples) {return false}
    if !SwiftProtobuf.Internal.areAllInitialized(self.ppiSamples) {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._day) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.samples) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.ppiSamples) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._day {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.samples.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.samples, fieldNumber: 2)
    }
    if !self.ppiSamples.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.ppiSamples, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbAutomaticSampleSessions, rhs: Data_PbAutomaticSampleSessions) -> Bool {
    if lhs._day != rhs._day {return false}
    if lhs.samples != rhs.samples {return false}
    if lhs.ppiSamples != rhs.ppiSamples {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Data_PbAutomaticHeartRateSamples: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbAutomaticHeartRateSamples"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}trigger_type\0\u{1}time\0\u{3}heart_rate\0")

  public var isInitialized: Bool {
    if self._triggerType == nil {return false}
    if self._time == nil {return false}
    if let v = self._time, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._triggerType) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._time) }()
      case 3: try { try decoder.decodeRepeatedUInt32Field(value: &self.heartRate) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._triggerType {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._time {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.heartRate.isEmpty {
      try visitor.visitPackedUInt32Field(value: self.heartRate, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbAutomaticHeartRateSamples, rhs: Data_PbAutomaticHeartRateSamples) -> Bool {
    if lhs._triggerType != rhs._triggerType {return false}
    if lhs._time != rhs._time {return false}
    if lhs.heartRate != rhs.heartRate {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Data_PbPpIntervalAutoSamples: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPpIntervalAutoSamples"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}trigger_type\0\u{3}recording_time\0\u{1}ppi\0")

  public var isInitialized: Bool {
    if let v = self._recordingTime, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._triggerType) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._recordingTime) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._ppi) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._triggerType {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._recordingTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._ppi {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbPpIntervalAutoSamples, rhs: Data_PbPpIntervalAutoSamples) -> Bool {
    if lhs._triggerType != rhs._triggerType {return false}
    if lhs._recordingTime != rhs._recordingTime {return false}
    if lhs._ppi != rhs._ppi {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Data_PbPpIntervalAutoSamples.PbPpIntervalRecordingTriggerType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PPI_TRIGGER_TYPE_UNDEFINED\0\u{1}PPI_TRIGGER_TYPE_AUTOMATIC\0\u{1}PPI_TRIGGER_TYPE_MANUAL\0")
}
