// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: dailysummary.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// DSUM.BPB=PbDailySummary

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct Data_PbActivityClassTimes: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var timeNonWear: PbDuration {
    get {_storage._timeNonWear ?? PbDuration()}
    set {_uniqueStorage()._timeNonWear = newValue}
  }
  /// Returns true if `timeNonWear` has been explicitly set.
  public var hasTimeNonWear: Bool {_storage._timeNonWear != nil}
  /// Clears the value of `timeNonWear`. Subsequent reads from it will return its default value.
  public mutating func clearTimeNonWear() {_uniqueStorage()._timeNonWear = nil}

  public var timeSleep: PbDuration {
    get {_storage._timeSleep ?? PbDuration()}
    set {_uniqueStorage()._timeSleep = newValue}
  }
  /// Returns true if `timeSleep` has been explicitly set.
  public var hasTimeSleep: Bool {_storage._timeSleep != nil}
  /// Clears the value of `timeSleep`. Subsequent reads from it will return its default value.
  public mutating func clearTimeSleep() {_uniqueStorage()._timeSleep = nil}

  public var timeSedentary: PbDuration {
    get {_storage._timeSedentary ?? PbDuration()}
    set {_uniqueStorage()._timeSedentary = newValue}
  }
  /// Returns true if `timeSedentary` has been explicitly set.
  public var hasTimeSedentary: Bool {_storage._timeSedentary != nil}
  /// Clears the value of `timeSedentary`. Subsequent reads from it will return its default value.
  public mutating func clearTimeSedentary() {_uniqueStorage()._timeSedentary = nil}

  public var timeLightActivity: PbDuration {
    get {_storage._timeLightActivity ?? PbDuration()}
    set {_uniqueStorage()._timeLightActivity = newValue}
  }
  /// Returns true if `timeLightActivity` has been explicitly set.
  public var hasTimeLightActivity: Bool {_storage._timeLightActivity != nil}
  /// Clears the value of `timeLightActivity`. Subsequent reads from it will return its default value.
  public mutating func clearTimeLightActivity() {_uniqueStorage()._timeLightActivity = nil}

  public var timeContinuousModerate: PbDuration {
    get {_storage._timeContinuousModerate ?? PbDuration()}
    set {_uniqueStorage()._timeContinuousModerate = newValue}
  }
  /// Returns true if `timeContinuousModerate` has been explicitly set.
  public var hasTimeContinuousModerate: Bool {_storage._timeContinuousModerate != nil}
  /// Clears the value of `timeContinuousModerate`. Subsequent reads from it will return its default value.
  public mutating func clearTimeContinuousModerate() {_uniqueStorage()._timeContinuousModerate = nil}

  public var timeIntermittentModerate: PbDuration {
    get {_storage._timeIntermittentModerate ?? PbDuration()}
    set {_uniqueStorage()._timeIntermittentModerate = newValue}
  }
  /// Returns true if `timeIntermittentModerate` has been explicitly set.
  public var hasTimeIntermittentModerate: Bool {_storage._timeIntermittentModerate != nil}
  /// Clears the value of `timeIntermittentModerate`. Subsequent reads from it will return its default value.
  public mutating func clearTimeIntermittentModerate() {_uniqueStorage()._timeIntermittentModerate = nil}

  public var timeContinuousVigorous: PbDuration {
    get {_storage._timeContinuousVigorous ?? PbDuration()}
    set {_uniqueStorage()._timeContinuousVigorous = newValue}
  }
  /// Returns true if `timeContinuousVigorous` has been explicitly set.
  public var hasTimeContinuousVigorous: Bool {_storage._timeContinuousVigorous != nil}
  /// Clears the value of `timeContinuousVigorous`. Subsequent reads from it will return its default value.
  public mutating func clearTimeContinuousVigorous() {_uniqueStorage()._timeContinuousVigorous = nil}

  public var timeIntermittentVigorous: PbDuration {
    get {_storage._timeIntermittentVigorous ?? PbDuration()}
    set {_uniqueStorage()._timeIntermittentVigorous = newValue}
  }
  /// Returns true if `timeIntermittentVigorous` has been explicitly set.
  public var hasTimeIntermittentVigorous: Bool {_storage._timeIntermittentVigorous != nil}
  /// Clears the value of `timeIntermittentVigorous`. Subsequent reads from it will return its default value.
  public mutating func clearTimeIntermittentVigorous() {_uniqueStorage()._timeIntermittentVigorous = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public nonisolated struct Data_PbActivityGoalSummary: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var activityGoal: Float {
    get {_activityGoal ?? 0}
    set {_activityGoal = newValue}
  }
  /// Returns true if `activityGoal` has been explicitly set.
  public var hasActivityGoal: Bool {self._activityGoal != nil}
  /// Clears the value of `activityGoal`. Subsequent reads from it will return its default value.
  public mutating func clearActivityGoal() {self._activityGoal = nil}

  public var achievedActivity: Float {
    get {_achievedActivity ?? 0}
    set {_achievedActivity = newValue}
  }
  /// Returns true if `achievedActivity` has been explicitly set.
  public var hasAchievedActivity: Bool {self._achievedActivity != nil}
  /// Clears the value of `achievedActivity`. Subsequent reads from it will return its default value.
  public mutating func clearAchievedActivity() {self._achievedActivity = nil}

  public var timeToGoUp: PbDuration {
    get {_timeToGoUp ?? PbDuration()}
    set {_timeToGoUp = newValue}
  }
  /// Returns true if `timeToGoUp` has been explicitly set.
  public var hasTimeToGoUp: Bool {self._timeToGoUp != nil}
  /// Clears the value of `timeToGoUp`. Subsequent reads from it will return its default value.
  public mutating func clearTimeToGoUp() {self._timeToGoUp = nil}

  public var timeToGoWalk: PbDuration {
    get {_timeToGoWalk ?? PbDuration()}
    set {_timeToGoWalk = newValue}
  }
  /// Returns true if `timeToGoWalk` has been explicitly set.
  public var hasTimeToGoWalk: Bool {self._timeToGoWalk != nil}
  /// Clears the value of `timeToGoWalk`. Subsequent reads from it will return its default value.
  public mutating func clearTimeToGoWalk() {self._timeToGoWalk = nil}

  public var timeToGoJog: PbDuration {
    get {_timeToGoJog ?? PbDuration()}
    set {_timeToGoJog = newValue}
  }
  /// Returns true if `timeToGoJog` has been explicitly set.
  public var hasTimeToGoJog: Bool {self._timeToGoJog != nil}
  /// Clears the value of `timeToGoJog`. Subsequent reads from it will return its default value.
  public mutating func clearTimeToGoJog() {self._timeToGoJog = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _activityGoal: Float? = nil
  fileprivate var _achievedActivity: Float? = nil
  fileprivate var _timeToGoUp: PbDuration? = nil
  fileprivate var _timeToGoWalk: PbDuration? = nil
  fileprivate var _timeToGoJog: PbDuration? = nil
}

public nonisolated struct Data_PbDailySummary: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var date: PbDate {
    get {_storage._date ?? PbDate()}
    set {_uniqueStorage()._date = newValue}
  }
  /// Returns true if `date` has been explicitly set.
  public var hasDate: Bool {_storage._date != nil}
  /// Clears the value of `date`. Subsequent reads from it will return its default value.
  public mutating func clearDate() {_uniqueStorage()._date = nil}

  public var steps: UInt32 {
    get {_storage._steps ?? 0}
    set {_uniqueStorage()._steps = newValue}
  }
  /// Returns true if `steps` has been explicitly set.
  public var hasSteps: Bool {_storage._steps != nil}
  /// Clears the value of `steps`. Subsequent reads from it will return its default value.
  public mutating func clearSteps() {_uniqueStorage()._steps = nil}

  public var activityCalories: UInt32 {
    get {_storage._activityCalories ?? 0}
    set {_uniqueStorage()._activityCalories = newValue}
  }
  /// Returns true if `activityCalories` has been explicitly set.
  public var hasActivityCalories: Bool {_storage._activityCalories != nil}
  /// Clears the value of `activityCalories`. Subsequent reads from it will return its default value.
  public mutating func clearActivityCalories() {_uniqueStorage()._activityCalories = nil}

  public var trainingCalories: UInt32 {
    get {_storage._trainingCalories ?? 0}
    set {_uniqueStorage()._trainingCalories = newValue}
  }
  /// Returns true if `trainingCalories` has been explicitly set.
  public var hasTrainingCalories: Bool {_storage._trainingCalories != nil}
  /// Clears the value of `trainingCalories`. Subsequent reads from it will return its default value.
  public mutating func clearTrainingCalories() {_uniqueStorage()._trainingCalories = nil}

  public var bmrCalories: UInt32 {
    get {_storage._bmrCalories ?? 0}
    set {_uniqueStorage()._bmrCalories = newValue}
  }
  /// Returns true if `bmrCalories` has been explicitly set.
  public var hasBmrCalories: Bool {_storage._bmrCalories != nil}
  /// Clears the value of `bmrCalories`. Subsequent reads from it will return its default value.
  public mutating func clearBmrCalories() {_uniqueStorage()._bmrCalories = nil}

  public var activityGoalSummary: Data_PbActivityGoalSummary {
    get {_storage._activityGoalSummary ?? Data_PbActivityGoalSummary()}
    set {_uniqueStorage()._activityGoalSummary = newValue}
  }
  /// Returns true if `activityGoalSummary` has been explicitly set.
  public var hasActivityGoalSummary: Bool {_storage._activityGoalSummary != nil}
  /// Clears the value of `activityGoalSummary`. Subsequent reads from it will return its default value.
  public mutating func clearActivityGoalSummary() {_uniqueStorage()._activityGoalSummary = nil}

  public var activityClassTimes: Data_PbActivityClassTimes {
    get {_storage._activityClassTimes ?? Data_PbActivityClassTimes()}
    set {_uniqueStorage()._activityClassTimes = newValue}
  }
  /// Returns true if `activityClassTimes` has been explicitly set.
  public var hasActivityClassTimes: Bool {_storage._activityClassTimes != nil}
  /// Clears the value of `activityClassTimes`. Subsequent reads from it will return its default value.
  public mutating func clearActivityClassTimes() {_uniqueStorage()._activityClassTimes = nil}

  public var activityDistance: Float {
    get {_storage._activityDistance ?? 0}
    set {_uniqueStorage()._activityDistance = newValue}
  }
  /// Returns true if `activityDistance` has been explicitly set.
  public var hasActivityDistance: Bool {_storage._activityDistance != nil}
  /// Clears the value of `activityDistance`. Subsequent reads from it will return its default value.
  public mutating func clearActivityDistance() {_uniqueStorage()._activityDistance = nil}

  public var dailyBalanceFeedback: PbDailyBalanceFeedback {
    get {_storage._dailyBalanceFeedback ?? .dbNotCalculated}
    set {_uniqueStorage()._dailyBalanceFeedback = newValue}
  }
  /// Returns true if `dailyBalanceFeedback` has been explicitly set.
  public var hasDailyBalanceFeedback: Bool {_storage._dailyBalanceFeedback != nil}
  /// Clears the value of `dailyBalanceFeedback`. Subsequent reads from it will return its default value.
  public mutating func clearDailyBalanceFeedback() {_uniqueStorage()._dailyBalanceFeedback = nil}

  public var readinessForSpeedAndStrengthTraining: PbReadinessForSpeedAndStrengthTraining {
    get {_storage._readinessForSpeedAndStrengthTraining ?? .rsstNotCalculated}
    set {_uniqueStorage()._readinessForSpeedAndStrengthTraining = newValue}
  }
  /// Returns true if `readinessForSpeedAndStrengthTraining` has been explicitly set.
  public var hasReadinessForSpeedAndStrengthTraining: Bool {_storage._readinessForSpeedAndStrengthTraining != nil}
  /// Clears the value of `readinessForSpeedAndStrengthTraining`. Subsequent reads from it will return its default value.
  public mutating func clearReadinessForSpeedAndStrengthTraining() {_uniqueStorage()._readinessForSpeedAndStrengthTraining = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "data"

nonisolated extension Data_PbActivityClassTimes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbActivityClassTimes"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}time_non_wear\0\u{3}time_sleep\0\u{3}time_sedentary\0\u{3}time_light_activity\0\u{3}time_continuous_moderate\0\u{3}time_intermittent_moderate\0\u{3}time_continuous_vigorous\0\u{3}time_intermittent_vigorous\0")

  fileprivate class _StorageClass {
    var _timeNonWear: PbDuration? = nil
    var _timeSleep: PbDuration? = nil
    var _timeSedentary: PbDuration? = nil
    var _timeLightActivity: PbDuration? = nil
    var _timeContinuousModerate: PbDuration? = nil
    var _timeIntermittentModerate: PbDuration? = nil
    var _timeContinuousVigorous: PbDuration? = nil
    var _timeIntermittentVigorous: PbDuration? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _timeNonWear = source._timeNonWear
      _timeSleep = source._timeSleep
      _timeSedentary = source._timeSedentary
      _timeLightActivity = source._timeLightActivity
      _timeContinuousModerate = source._timeContinuousModerate
      _timeIntermittentModerate = source._timeIntermittentModerate
      _timeContinuousVigorous = source._timeContinuousVigorous
      _timeIntermittentVigorous = source._timeIntermittentVigorous
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public var isInitialized: Bool {
    return withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._timeNonWear == nil {return false}
      if _storage._timeSleep == nil {return false}
      if _storage._timeSedentary == nil {return false}
      if _storage._timeLightActivity == nil {return false}
      if _storage._timeContinuousModerate == nil {return false}
      if _storage._timeIntermittentModerate == nil {return false}
      if _storage._timeContinuousVigorous == nil {return false}
      if _storage._timeIntermittentVigorous == nil {return false}
      return true
    }
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._timeNonWear) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._timeSleep) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._timeSedentary) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._timeLightActivity) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._timeContinuousModerate) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._timeIntermittentModerate) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._timeContinuousVigorous) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._timeIntermittentVigorous) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._timeNonWear {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._timeSleep {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._timeSedentary {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._timeLightActivity {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._timeContinuousModerate {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._timeIntermittentModerate {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._timeContinuousVigorous {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._timeIntermittentVigorous {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbActivityClassTimes, rhs: Data_PbActivityClassTimes) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._timeNonWear != rhs_storage._timeNonWear {return false}
        if _storage._timeSleep != rhs_storage._timeSleep {return false}
        if _storage._timeSedentary != rhs_storage._timeSedentary {return false}
        if _storage._timeLightActivity != rhs_storage._timeLightActivity {return false}
        if _storage._timeContinuousModerate != rhs_storage._timeContinuousModerate {return false}
        if _storage._timeIntermittentModerate != rhs_storage._timeIntermittentModerate {return false}
        if _storage._timeContinuousVigorous != rhs_storage._timeContinuousVigorous {return false}
        if _storage._timeIntermittentVigorous != rhs_storage._timeIntermittentVigorous {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Data_PbActivityGoalSummary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbActivityGoalSummary"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}activity_goal\0\u{3}achieved_activity\0\u{3}time_to_go_up\0\u{3}time_to_go_walk\0\u{3}time_to_go_jog\0")

  public var isInitialized: Bool {
    if self._activityGoal == nil {return false}
    if self._achievedActivity == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self._activityGoal) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self._achievedActivity) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._timeToGoUp) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._timeToGoWalk) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._timeToGoJog) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._activityGoal {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._achievedActivity {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._timeToGoUp {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._timeToGoWalk {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._timeToGoJog {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbActivityGoalSummary, rhs: Data_PbActivityGoalSummary) -> Bool {
    if lhs._activityGoal != rhs._activityGoal {return false}
    if lhs._achievedActivity != rhs._achievedActivity {return false}
    if lhs._timeToGoUp != rhs._timeToGoUp {return false}
    if lhs._timeToGoWalk != rhs._timeToGoWalk {return false}
    if lhs._timeToGoJog != rhs._timeToGoJog {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Data_PbDailySummary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbDailySummary"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}date\0\u{1}steps\0\u{3}activity_calories\0\u{3}training_calories\0\u{3}bmr_calories\0\u{3}activity_goal_summary\0\u{3}activity_class_times\0\u{3}activity_distance\0\u{3}daily_balance_feedback\0\u{3}readiness_for_speed_and_strength_training\0")

  fileprivate class _StorageClass {
    var _date: PbDate? = nil
    var _steps: UInt32? = nil
    var _activityCalories: UInt32? = nil
    var _trainingCalories: UInt32? = nil
    var _bmrCalories: UInt32? = nil
    var _activityGoalSummary: Data_PbActivityGoalSummary? = nil
    var _activityClassTimes: Data_PbActivityClassTimes? = nil
    var _activityDistance: Float? = nil
    var _dailyBalanceFeedback: PbDailyBalanceFeedback? = nil
    var _readinessForSpeedAndStrengthTraining: PbReadinessForSpeedAndStrengthTraining? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _date = source._date
      _steps = source._steps
      _activityCalories = source._activityCalories
      _trainingCalories = source._trainingCalories
      _bmrCalories = source._bmrCalories
      _activityGoalSummary = source._activityGoalSummary
      _activityClassTimes = source._activityClassTimes
      _activityDistance = source._activityDistance
      _dailyBalanceFeedback = source._dailyBalanceFeedback
      _readinessForSpeedAndStrengthTraining = source._readinessForSpeedAndStrengthTraining
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public var isInitialized: Bool {
    return withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._date == nil {return false}
      if let v = _storage._date, !v.isInitialized {return false}
      if let v = _storage._activityGoalSummary, !v.isInitialized {return false}
      if let v = _storage._activityClassTimes, !v.isInitialized {return false}
      return true
    }
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._date) }()
        case 2: try { try decoder.decodeSingularUInt32Field(value: &_storage._steps) }()
        case 3: try { try decoder.decodeSingularUInt32Field(value: &_storage._activityCalories) }()
        case 4: try { try decoder.decodeSingularUInt32Field(value: &_storage._trainingCalories) }()
        case 5: try { try decoder.decodeSingularUInt32Field(value: &_storage._bmrCalories) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._activityGoalSummary) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._activityClassTimes) }()
        case 8: try { try decoder.decodeSingularFloatField(value: &_storage._activityDistance) }()
        case 9: try { try decoder.decodeSingularEnumField(value: &_storage._dailyBalanceFeedback) }()
        case 10: try { try decoder.decodeSingularEnumField(value: &_storage._readinessForSpeedAndStrengthTraining) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._date {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._steps {
        try visitor.visitSingularUInt32Field(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._activityCalories {
        try visitor.visitSingularUInt32Field(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._trainingCalories {
        try visitor.visitSingularUInt32Field(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._bmrCalories {
        try visitor.visitSingularUInt32Field(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._activityGoalSummary {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._activityClassTimes {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._activityDistance {
        try visitor.visitSingularFloatField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._dailyBalanceFeedback {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._readinessForSpeedAndStrengthTraining {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 10)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbDailySummary, rhs: Data_PbDailySummary) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._date != rhs_storage._date {return false}
        if _storage._steps != rhs_storage._steps {return false}
        if _storage._activityCalories != rhs_storage._activityCalories {return false}
        if _storage._trainingCalories != rhs_storage._trainingCalories {return false}
        if _storage._bmrCalories != rhs_storage._bmrCalories {return false}
        if _storage._activityGoalSummary != rhs_storage._activityGoalSummary {return false}
        if _storage._activityClassTimes != rhs_storage._activityClassTimes {return false}
        if _storage._activityDistance != rhs_storage._activityDistance {return false}
        if _storage._dailyBalanceFeedback != rhs_storage._dailyBalanceFeedback {return false}
        if _storage._readinessForSpeedAndStrengthTraining != rhs_storage._readinessForSpeedAndStrengthTraining {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
