// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: device.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// DEVICE.BPB=PbDeviceInfo

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct Data_PbDeviceInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceVersion: PbVersion {
    get {_deviceVersion ?? PbVersion()}
    set {_deviceVersion = newValue}
  }
  /// Returns true if `deviceVersion` has been explicitly set.
  public var hasDeviceVersion: Bool {self._deviceVersion != nil}
  /// Clears the value of `deviceVersion`. Subsequent reads from it will return its default value.
  public mutating func clearDeviceVersion() {self._deviceVersion = nil}

  public var modelName: String {
    get {_modelName ?? String()}
    set {_modelName = newValue}
  }
  /// Returns true if `modelName` has been explicitly set.
  public var hasModelName: Bool {self._modelName != nil}
  /// Clears the value of `modelName`. Subsequent reads from it will return its default value.
  public mutating func clearModelName() {self._modelName = nil}

  public var hardwareCode: String {
    get {_hardwareCode ?? String()}
    set {_hardwareCode = newValue}
  }
  /// Returns true if `hardwareCode` has been explicitly set.
  public var hasHardwareCode: Bool {self._hardwareCode != nil}
  /// Clears the value of `hardwareCode`. Subsequent reads from it will return its default value.
  public mutating func clearHardwareCode() {self._hardwareCode = nil}

  public var capabilities: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _deviceVersion: PbVersion? = nil
  fileprivate var _modelName: String? = nil
  fileprivate var _hardwareCode: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "data"

nonisolated extension Data_PbDeviceInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbDeviceInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{3}device_version\0\u{4}\u{4}model_name\0\u{3}hardware_code\0\u{2}\u{a}capabilities\0")

  public var isInitialized: Bool {
    if let v = self._deviceVersion, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 3: try { try decoder.decodeSingularMessageField(value: &self._deviceVersion) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._modelName) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._hardwareCode) }()
      case 18: try { try decoder.decodeRepeatedStringField(value: &self.capabilities) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._deviceVersion {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._modelName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._hardwareCode {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    if !self.capabilities.isEmpty {
      try visitor.visitRepeatedStringField(value: self.capabilities, fieldNumber: 18)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbDeviceInfo, rhs: Data_PbDeviceInfo) -> Bool {
    if lhs._deviceVersion != rhs._deviceVersion {return false}
    if lhs._modelName != rhs._modelName {return false}
    if lhs._hardwareCode != rhs._hardwareCode {return false}
    if lhs.capabilities != rhs.capabilities {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
