// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: nanopb.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Custom options for defining:
/// - Maximum size of string/bytes
/// - Maximum number of elements in array
///
/// These are used by nanopb to generate statically allocable structures
/// for memory-limited environments.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct NanoPBOptions: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var maxSize: Int32 {
    get {_maxSize ?? 0}
    set {_maxSize = newValue}
  }
  /// Returns true if `maxSize` has been explicitly set.
  public var hasMaxSize: Bool {self._maxSize != nil}
  /// Clears the value of `maxSize`. Subsequent reads from it will return its default value.
  public mutating func clearMaxSize() {self._maxSize = nil}

  public var maxCount: Int32 {
    get {_maxCount ?? 0}
    set {_maxCount = newValue}
  }
  /// Returns true if `maxCount` has been explicitly set.
  public var hasMaxCount: Bool {self._maxCount != nil}
  /// Clears the value of `maxCount`. Subsequent reads from it will return its default value.
  public mutating func clearMaxCount() {self._maxCount = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _maxSize: Int32? = nil
  fileprivate var _maxCount: Int32? = nil
}

// MARK: - Extension support defined in nanopb.proto.

// MARK: - Extension Properties

// Swift Extensions on the extended Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

nonisolated extension SwiftProtobuf.Google_Protobuf_FieldOptions {

  public var nanopb: NanoPBOptions {
    get {return getExtensionValue(ext: Extensions_nanopb) ?? NanoPBOptions()}
    set {setExtensionValue(ext: Extensions_nanopb, value: newValue)}
  }
  /// Returns true if extension `Extensions_nanopb`
  /// has been explicitly set.
  public var hasNanopb: Bool {
    return hasExtensionValue(ext: Extensions_nanopb)
  }
  /// Clears the value of extension `Extensions_nanopb`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearNanopb() {
    clearExtensionValue(ext: Extensions_nanopb)
  }

}

// MARK: - File's ExtensionMap: Nanopb_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
public nonisolated let Nanopb_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  Extensions_nanopb
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

public nonisolated let Extensions_nanopb = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalMessageExtensionField<NanoPBOptions>, SwiftProtobuf.Google_Protobuf_FieldOptions>(
  _protobuf_fieldNumber: 1010,
  fieldName: "nanopb"
)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

nonisolated extension NanoPBOptions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "NanoPBOptions"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}max_size\0\u{3}max_count\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._maxSize) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._maxCount) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._maxSize {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._maxCount {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: NanoPBOptions, rhs: NanoPBOptions) -> Bool {
    if lhs._maxSize != rhs._maxSize {return false}
    if lhs._maxCount != rhs._maxCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
