// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: pftp_response.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct Protocol_PbPFtpEntry: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String {
    get {_storage._name ?? String()}
    set {_uniqueStorage()._name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  public var hasName: Bool {_storage._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  public mutating func clearName() {_uniqueStorage()._name = nil}

  public var size: UInt64 {
    get {_storage._size ?? 0}
    set {_uniqueStorage()._size = newValue}
  }
  /// Returns true if `size` has been explicitly set.
  public var hasSize: Bool {_storage._size != nil}
  /// Clears the value of `size`. Subsequent reads from it will return its default value.
  public mutating func clearSize() {_uniqueStorage()._size = nil}

  public var created: PbSystemDateTime {
    get {_storage._created ?? PbSystemDateTime()}
    set {_uniqueStorage()._created = newValue}
  }
  /// Returns true if `created` has been explicitly set.
  public var hasCreated: Bool {_storage._created != nil}
  /// Clears the value of `created`. Subsequent reads from it will return its default value.
  public mutating func clearCreated() {_uniqueStorage()._created = nil}

  public var modified: PbSystemDateTime {
    get {_storage._modified ?? PbSystemDateTime()}
    set {_uniqueStorage()._modified = newValue}
  }
  /// Returns true if `modified` has been explicitly set.
  public var hasModified: Bool {_storage._modified != nil}
  /// Clears the value of `modified`. Subsequent reads from it will return its default value.
  public mutating func clearModified() {_uniqueStorage()._modified = nil}

  public var touched: PbSystemDateTime {
    get {_storage._touched ?? PbSystemDateTime()}
    set {_uniqueStorage()._touched = newValue}
  }
  /// Returns true if `touched` has been explicitly set.
  public var hasTouched: Bool {_storage._touched != nil}
  /// Clears the value of `touched`. Subsequent reads from it will return its default value.
  public mutating func clearTouched() {_uniqueStorage()._touched = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public nonisolated struct Protocol_PbPFtpDirectory: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var entries: [Protocol_PbPFtpEntry] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Protocol_PbRequestRecordingStatusResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var recordingOn: Bool {
    get {_recordingOn ?? false}
    set {_recordingOn = newValue}
  }
  /// Returns true if `recordingOn` has been explicitly set.
  public var hasRecordingOn: Bool {self._recordingOn != nil}
  /// Clears the value of `recordingOn`. Subsequent reads from it will return its default value.
  public mutating func clearRecordingOn() {self._recordingOn = nil}

  public var sampleDataIdentifier: String {
    get {_sampleDataIdentifier ?? String()}
    set {_sampleDataIdentifier = newValue}
  }
  /// Returns true if `sampleDataIdentifier` has been explicitly set.
  public var hasSampleDataIdentifier: Bool {self._sampleDataIdentifier != nil}
  /// Clears the value of `sampleDataIdentifier`. Subsequent reads from it will return its default value.
  public mutating func clearSampleDataIdentifier() {self._sampleDataIdentifier = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _recordingOn: Bool? = nil
  fileprivate var _sampleDataIdentifier: String? = nil
}

public nonisolated struct Protocol_PbPFtpDiskSpaceResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var fragmentSize: UInt32 {
    get {_fragmentSize ?? 0}
    set {_fragmentSize = newValue}
  }
  /// Returns true if `fragmentSize` has been explicitly set.
  public var hasFragmentSize: Bool {self._fragmentSize != nil}
  /// Clears the value of `fragmentSize`. Subsequent reads from it will return its default value.
  public mutating func clearFragmentSize() {self._fragmentSize = nil}

  public var totalFragments: UInt64 {
    get {_totalFragments ?? 0}
    set {_totalFragments = newValue}
  }
  /// Returns true if `totalFragments` has been explicitly set.
  public var hasTotalFragments: Bool {self._totalFragments != nil}
  /// Clears the value of `totalFragments`. Subsequent reads from it will return its default value.
  public mutating func clearTotalFragments() {self._totalFragments = nil}

  public var freeFragments: UInt64 {
    get {_freeFragments ?? 0}
    set {_freeFragments = newValue}
  }
  /// Returns true if `freeFragments` has been explicitly set.
  public var hasFreeFragments: Bool {self._freeFragments != nil}
  /// Clears the value of `freeFragments`. Subsequent reads from it will return its default value.
  public mutating func clearFreeFragments() {self._freeFragments = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _fragmentSize: UInt32? = nil
  fileprivate var _totalFragments: UInt64? = nil
  fileprivate var _freeFragments: UInt64? = nil
}

///
/// Response data to RESUME_EXERCISE query in pftp_request.proto.
public nonisolated struct Protocol_PbPftpResumeExerciseResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var result: Protocol_PbPftpResumeExerciseResult.PbResumeExerciseResult {
    get {_result ?? .resultOther}
    set {_result = newValue}
  }
  /// Returns true if `result` has been explicitly set.
  public var hasResult: Bool {self._result != nil}
  /// Clears the value of `result`. Subsequent reads from it will return its default value.
  public mutating func clearResult() {self._result = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum PbResumeExerciseResult: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case resultOther = 0
    case resultSuccess = 1
    case resultExeNotRunning = 2
    case resultNotPaused = 3

    public init() {
      self = .resultOther
    }

  }

  public init() {}

  fileprivate var _result: Protocol_PbPftpResumeExerciseResult.PbResumeExerciseResult? = nil
}

///
/// Response data to GET_EXERCISE_STATUS query in pftp_request.proto.
public nonisolated struct Protocol_PbPftpGetExerciseStatusResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var exerciseState: Protocol_PbPftpGetExerciseStatusResult.PbExerciseState {
    get {_exerciseState ?? .exerciseStateOther}
    set {_exerciseState = newValue}
  }
  /// Returns true if `exerciseState` has been explicitly set.
  public var hasExerciseState: Bool {self._exerciseState != nil}
  /// Clears the value of `exerciseState`. Subsequent reads from it will return its default value.
  public mutating func clearExerciseState() {self._exerciseState = nil}

  public var exerciseType: Protocol_PbPftpGetExerciseStatusResult.PbExerciseType {
    get {_exerciseType ?? .exerciseTypeOther}
    set {_exerciseType = newValue}
  }
  /// Returns true if `exerciseType` has been explicitly set.
  public var hasExerciseType: Bool {self._exerciseType != nil}
  /// Clears the value of `exerciseType`. Subsequent reads from it will return its default value.
  public mutating func clearExerciseType() {self._exerciseType = nil}

  public var sportIdentifier: PbSportIdentifier {
    get {_sportIdentifier ?? PbSportIdentifier()}
    set {_sportIdentifier = newValue}
  }
  /// Returns true if `sportIdentifier` has been explicitly set.
  public var hasSportIdentifier: Bool {self._sportIdentifier != nil}
  /// Clears the value of `sportIdentifier`. Subsequent reads from it will return its default value.
  public mutating func clearSportIdentifier() {self._sportIdentifier = nil}

  public var startTime: PbLocalDateTime {
    get {_startTime ?? PbLocalDateTime()}
    set {_startTime = newValue}
  }
  /// Returns true if `startTime` has been explicitly set.
  public var hasStartTime: Bool {self._startTime != nil}
  /// Clears the value of `startTime`. Subsequent reads from it will return its default value.
  public mutating func clearStartTime() {self._startTime = nil}

  public var dmDirectoryPath: String {
    get {_dmDirectoryPath ?? String()}
    set {_dmDirectoryPath = newValue}
  }
  /// Returns true if `dmDirectoryPath` has been explicitly set.
  public var hasDmDirectoryPath: Bool {self._dmDirectoryPath != nil}
  /// Clears the value of `dmDirectoryPath`. Subsequent reads from it will return its default value.
  public mutating func clearDmDirectoryPath() {self._dmDirectoryPath = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum PbExerciseState: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case exerciseStateOther = 0
    case exerciseStateRunning = 1
    case exerciseStatePaused = 2
    case exerciseStateOff = 3

    public init() {
      self = .exerciseStateOther
    }

  }

  public nonisolated enum PbExerciseType: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case exerciseTypeOther = 0
    case exerciseTypeNormal = 1
    case exerciseTypeRemote = 2
    case exerciseTypeAutomatic = 3
    case exerciseTypeDataMerge = 4

    public init() {
      self = .exerciseTypeOther
    }

  }

  public init() {}

  fileprivate var _exerciseState: Protocol_PbPftpGetExerciseStatusResult.PbExerciseState? = nil
  fileprivate var _exerciseType: Protocol_PbPftpGetExerciseStatusResult.PbExerciseType? = nil
  fileprivate var _sportIdentifier: PbSportIdentifier? = nil
  fileprivate var _startTime: PbLocalDateTime? = nil
  fileprivate var _dmDirectoryPath: String? = nil
}

///
/// Response data to START_DM_EXERCISE query in pftp_request.proto.
public nonisolated struct Protocol_PbPftpStartDmExerciseResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var result: Protocol_PbPftpStartDmExerciseResult.PbStartDmExerciseResult {
    get {_result ?? .resultOther}
    set {_result = newValue}
  }
  /// Returns true if `result` has been explicitly set.
  public var hasResult: Bool {self._result != nil}
  /// Clears the value of `result`. Subsequent reads from it will return its default value.
  public mutating func clearResult() {self._result = nil}

  public var dmDirectoryPath: String {
    get {_dmDirectoryPath ?? String()}
    set {_dmDirectoryPath = newValue}
  }
  /// Returns true if `dmDirectoryPath` has been explicitly set.
  public var hasDmDirectoryPath: Bool {self._dmDirectoryPath != nil}
  /// Clears the value of `dmDirectoryPath`. Subsequent reads from it will return its default value.
  public mutating func clearDmDirectoryPath() {self._dmDirectoryPath = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum PbStartDmExerciseResult: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case resultOther = 0
    case resultSuccess = 1
    case resultExeOngoing = 2
    case resultLowBattery = 3
    case resultSdkMode = 4
    case resultUnknownSport = 5

    public init() {
      self = .resultOther
    }

  }

  public init() {}

  fileprivate var _result: Protocol_PbPftpStartDmExerciseResult.PbStartDmExerciseResult? = nil
  fileprivate var _dmDirectoryPath: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protocol"

nonisolated extension Protocol_PbPFtpEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPFtpEntry"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}size\0\u{1}created\0\u{1}modified\0\u{1}touched\0")

  fileprivate class _StorageClass {
    var _name: String? = nil
    var _size: UInt64? = nil
    var _created: PbSystemDateTime? = nil
    var _modified: PbSystemDateTime? = nil
    var _touched: PbSystemDateTime? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _name = source._name
      _size = source._size
      _created = source._created
      _modified = source._modified
      _touched = source._touched
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public var isInitialized: Bool {
    return withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._name == nil {return false}
      if _storage._size == nil {return false}
      if let v = _storage._created, !v.isInitialized {return false}
      if let v = _storage._modified, !v.isInitialized {return false}
      if let v = _storage._touched, !v.isInitialized {return false}
      return true
    }
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 2: try { try decoder.decodeSingularUInt64Field(value: &_storage._size) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._created) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._modified) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._touched) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._name {
        try visitor.visitSingularStringField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._size {
        try visitor.visitSingularUInt64Field(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._created {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._modified {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._touched {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPFtpEntry, rhs: Protocol_PbPFtpEntry) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._name != rhs_storage._name {return false}
        if _storage._size != rhs_storage._size {return false}
        if _storage._created != rhs_storage._created {return false}
        if _storage._modified != rhs_storage._modified {return false}
        if _storage._touched != rhs_storage._touched {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPFtpDirectory: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPFtpDirectory"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}entries\0")

  public var isInitialized: Bool {
    if !SwiftProtobuf.Internal.areAllInitialized(self.entries) {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.entries) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.entries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.entries, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPFtpDirectory, rhs: Protocol_PbPFtpDirectory) -> Bool {
    if lhs.entries != rhs.entries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbRequestRecordingStatusResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbRequestRecordingStatusResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}recording_on\0\u{3}sample_data_identifier\0")

  public var isInitialized: Bool {
    if self._recordingOn == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._recordingOn) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._sampleDataIdentifier) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._recordingOn {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._sampleDataIdentifier {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbRequestRecordingStatusResult, rhs: Protocol_PbRequestRecordingStatusResult) -> Bool {
    if lhs._recordingOn != rhs._recordingOn {return false}
    if lhs._sampleDataIdentifier != rhs._sampleDataIdentifier {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPFtpDiskSpaceResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPFtpDiskSpaceResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}fragment_size\0\u{3}total_fragments\0\u{3}free_fragments\0")

  public var isInitialized: Bool {
    if self._fragmentSize == nil {return false}
    if self._totalFragments == nil {return false}
    if self._freeFragments == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._fragmentSize) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self._totalFragments) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self._freeFragments) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._fragmentSize {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._totalFragments {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._freeFragments {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPFtpDiskSpaceResult, rhs: Protocol_PbPFtpDiskSpaceResult) -> Bool {
    if lhs._fragmentSize != rhs._fragmentSize {return false}
    if lhs._totalFragments != rhs._totalFragments {return false}
    if lhs._freeFragments != rhs._freeFragments {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPftpResumeExerciseResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPftpResumeExerciseResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}result\0")

  public var isInitialized: Bool {
    if self._result == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._result) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._result {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPftpResumeExerciseResult, rhs: Protocol_PbPftpResumeExerciseResult) -> Bool {
    if lhs._result != rhs._result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPftpResumeExerciseResult.PbResumeExerciseResult: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RESULT_OTHER\0\u{1}RESULT_SUCCESS\0\u{1}RESULT_EXE_NOT_RUNNING\0\u{1}RESULT_NOT_PAUSED\0")
}

nonisolated extension Protocol_PbPftpGetExerciseStatusResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPftpGetExerciseStatusResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}exercise_state\0\u{3}exercise_type\0\u{3}sport_identifier\0\u{3}start_time\0\u{3}dm_directory_path\0")

  public var isInitialized: Bool {
    if self._exerciseState == nil {return false}
    if let v = self._sportIdentifier, !v.isInitialized {return false}
    if let v = self._startTime, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._exerciseState) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self._exerciseType) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._sportIdentifier) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._startTime) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._dmDirectoryPath) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._exerciseState {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._exerciseType {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._sportIdentifier {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._startTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._dmDirectoryPath {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPftpGetExerciseStatusResult, rhs: Protocol_PbPftpGetExerciseStatusResult) -> Bool {
    if lhs._exerciseState != rhs._exerciseState {return false}
    if lhs._exerciseType != rhs._exerciseType {return false}
    if lhs._sportIdentifier != rhs._sportIdentifier {return false}
    if lhs._startTime != rhs._startTime {return false}
    if lhs._dmDirectoryPath != rhs._dmDirectoryPath {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPftpGetExerciseStatusResult.PbExerciseState: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0EXERCISE_STATE_OTHER\0\u{1}EXERCISE_STATE_RUNNING\0\u{1}EXERCISE_STATE_PAUSED\0\u{1}EXERCISE_STATE_OFF\0")
}

nonisolated extension Protocol_PbPftpGetExerciseStatusResult.PbExerciseType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0EXERCISE_TYPE_OTHER\0\u{1}EXERCISE_TYPE_NORMAL\0\u{1}EXERCISE_TYPE_REMOTE\0\u{1}EXERCISE_TYPE_AUTOMATIC\0\u{1}EXERCISE_TYPE_DATA_MERGE\0")
}

nonisolated extension Protocol_PbPftpStartDmExerciseResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPftpStartDmExerciseResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}result\0\u{3}dm_directory_path\0")

  public var isInitialized: Bool {
    if self._result == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._result) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._dmDirectoryPath) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._result {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._dmDirectoryPath {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPftpStartDmExerciseResult, rhs: Protocol_PbPftpStartDmExerciseResult) -> Bool {
    if lhs._result != rhs._result {return false}
    if lhs._dmDirectoryPath != rhs._dmDirectoryPath {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPftpStartDmExerciseResult.PbStartDmExerciseResult: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RESULT_OTHER\0\u{1}RESULT_SUCCESS\0\u{1}RESULT_EXE_ONGOING\0\u{1}RESULT_LOW_BATTERY\0\u{1}RESULT_SDK_MODE\0\u{1}RESULT_UNKNOWN_SPORT\0")
}
