// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: pftp_notification.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Protocol_PbPFtpHostToDevNotification: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case startSync = 0
  case stopSync = 1
  case reset = 2
  case initializeSession = 8
  case terminateSession = 9

  public init() {
    self = .startSync
  }

}

public nonisolated enum Protocol_PbPFtpDevToHostNotification: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case filesystemModified = 0
  case internalTestEvent = 1
  case idling = 2
  case batteryStatus = 3
  case inactivityAlert = 4
  case trainingSessionStatus = 5
  case syncRequired = 7
  case autosyncStatus = 8
  case pnsDhNotificationResponse = 9
  case pnsSettings = 10
  case startGpsMeasurement = 11
  case stopGpsMeasurement = 12
  case keepBackgroundAlive = 13
  case polarShellDhData = 14
  case mediaControlRequestDh = 15
  case mediaControlCommandDh = 16
  case mediaControlEnabled = 17
  case restApiEvent = 18
  case exerciseStatus = 19

  public init() {
    self = .filesystemModified
  }

}

public nonisolated enum Protocol_Action: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case created = 0
  case updated = 1
  case removed = 2

  public init() {
    self = .created
  }

}

public nonisolated enum Protocol_PbPFtpSyncTriggerSource: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case noSource = 0
  case user = 1
  case timed = 2
  case feature = 3

  public init() {
    self = .noSource
  }

}

public nonisolated enum Protocol_PbPftpPnsDHAttributeType: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case unknownAction = 1
  case positiveAction = 2
  case negativeAction = 3
  case clearAction = 4
  case aAction = 5
  case bAction = 6
  case cAction = 7
  case dAction = 8

  public init() {
    self = .unknownAction
  }

}

public nonisolated enum Protocol_MediaControlRequest: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case getMediaData = 1
  case getPlaybackState = 2

  public init() {
    self = .getMediaData
  }

}

public nonisolated enum Protocol_MediaControlCommand: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case play = 1
  case pause = 2
  case togglerPlayPause = 3
  case next = 4
  case previous = 5
  case fastForward = 6
  case fastBackward = 7
  case volumeUp = 8
  case volumeDown = 9

  public init() {
    self = .play
  }

}

public nonisolated struct Protocol_PbPFtpFactoryResetParams: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sleep: Bool {
    get {_sleep ?? false}
    set {_sleep = newValue}
  }
  /// Returns true if `sleep` has been explicitly set.
  public var hasSleep: Bool {self._sleep != nil}
  /// Clears the value of `sleep`. Subsequent reads from it will return its default value.
  public mutating func clearSleep() {self._sleep = nil}

  public var doFactoryDefaults: Bool {
    get {_doFactoryDefaults ?? true}
    set {_doFactoryDefaults = newValue}
  }
  /// Returns true if `doFactoryDefaults` has been explicitly set.
  public var hasDoFactoryDefaults: Bool {self._doFactoryDefaults != nil}
  /// Clears the value of `doFactoryDefaults`. Subsequent reads from it will return its default value.
  public mutating func clearDoFactoryDefaults() {self._doFactoryDefaults = nil}

  public var otaFwupdate: Bool {
    get {_otaFwupdate ?? false}
    set {_otaFwupdate = newValue}
  }
  /// Returns true if `otaFwupdate` has been explicitly set.
  public var hasOtaFwupdate: Bool {self._otaFwupdate != nil}
  /// Clears the value of `otaFwupdate`. Subsequent reads from it will return its default value.
  public mutating func clearOtaFwupdate() {self._otaFwupdate = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _sleep: Bool? = nil
  fileprivate var _doFactoryDefaults: Bool? = nil
  fileprivate var _otaFwupdate: Bool? = nil
}

public nonisolated struct Protocol_PbPFtpStopSyncParams: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var completed: Bool {
    get {_completed ?? false}
    set {_completed = newValue}
  }
  /// Returns true if `completed` has been explicitly set.
  public var hasCompleted: Bool {self._completed != nil}
  /// Clears the value of `completed`. Subsequent reads from it will return its default value.
  public mutating func clearCompleted() {self._completed = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _completed: Bool? = nil
}

public nonisolated struct Protocol_PbPFtpFilesystemModifiedParams: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var action: Protocol_Action {
    get {_action ?? .created}
    set {_action = newValue}
  }
  /// Returns true if `action` has been explicitly set.
  public var hasAction: Bool {self._action != nil}
  /// Clears the value of `action`. Subsequent reads from it will return its default value.
  public mutating func clearAction() {self._action = nil}

  public var path: String {
    get {_path ?? String()}
    set {_path = newValue}
  }
  /// Returns true if `path` has been explicitly set.
  public var hasPath: Bool {self._path != nil}
  /// Clears the value of `path`. Subsequent reads from it will return its default value.
  public mutating func clearPath() {self._path = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _action: Protocol_Action? = nil
  fileprivate var _path: String? = nil
}

public nonisolated struct Protocol_PbPFtpInactivityAlert: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var countdown: UInt32 {
    get {_countdown ?? 0}
    set {_countdown = newValue}
  }
  /// Returns true if `countdown` has been explicitly set.
  public var hasCountdown: Bool {self._countdown != nil}
  /// Clears the value of `countdown`. Subsequent reads from it will return its default value.
  public mutating func clearCountdown() {self._countdown = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _countdown: UInt32? = nil
}

public nonisolated struct Protocol_PbPFtpTrainingSessionStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var inprogress: Bool {
    get {_inprogress ?? false}
    set {_inprogress = newValue}
  }
  /// Returns true if `inprogress` has been explicitly set.
  public var hasInprogress: Bool {self._inprogress != nil}
  /// Clears the value of `inprogress`. Subsequent reads from it will return its default value.
  public mutating func clearInprogress() {self._inprogress = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _inprogress: Bool? = nil
}

public nonisolated struct Protocol_PbPFtpAutoSyncStatusParams: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var succeeded: Bool {
    get {_succeeded ?? false}
    set {_succeeded = newValue}
  }
  /// Returns true if `succeeded` has been explicitly set.
  public var hasSucceeded: Bool {self._succeeded != nil}
  /// Clears the value of `succeeded`. Subsequent reads from it will return its default value.
  public mutating func clearSucceeded() {self._succeeded = nil}

  public var description_p: String {
    get {_description_p ?? String()}
    set {_description_p = newValue}
  }
  /// Returns true if `description_p` has been explicitly set.
  public var hasDescription_p: Bool {self._description_p != nil}
  /// Clears the value of `description_p`. Subsequent reads from it will return its default value.
  public mutating func clearDescription_p() {self._description_p = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _succeeded: Bool? = nil
  fileprivate var _description_p: String? = nil
}

public nonisolated struct Protocol_PbPFtpSyncTrigger: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var source: Protocol_PbPFtpSyncTriggerSource {
    get {_source ?? .noSource}
    set {_source = newValue}
  }
  /// Returns true if `source` has been explicitly set.
  public var hasSource: Bool {self._source != nil}
  /// Clears the value of `source`. Subsequent reads from it will return its default value.
  public mutating func clearSource() {self._source = nil}

  public var featureName: String {
    get {_featureName ?? String()}
    set {_featureName = newValue}
  }
  /// Returns true if `featureName` has been explicitly set.
  public var hasFeatureName: Bool {self._featureName != nil}
  /// Clears the value of `featureName`. Subsequent reads from it will return its default value.
  public mutating func clearFeatureName() {self._featureName = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _source: Protocol_PbPFtpSyncTriggerSource? = nil
  fileprivate var _featureName: String? = nil
}

public nonisolated struct Protocol_PbPFtpSyncRequiredParams: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var syncTriggers: [Protocol_PbPFtpSyncTrigger] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Protocol_PbPFtpPolarShellMessageParams: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var polarShellMsgID: UInt32 {
    get {_polarShellMsgID ?? 0}
    set {_polarShellMsgID = newValue}
  }
  /// Returns true if `polarShellMsgID` has been explicitly set.
  public var hasPolarShellMsgID: Bool {self._polarShellMsgID != nil}
  /// Clears the value of `polarShellMsgID`. Subsequent reads from it will return its default value.
  public mutating func clearPolarShellMsgID() {self._polarShellMsgID = nil}

  public var data: String {
    get {_data ?? String()}
    set {_data = newValue}
  }
  /// Returns true if `data` has been explicitly set.
  public var hasData: Bool {self._data != nil}
  /// Clears the value of `data`. Subsequent reads from it will return its default value.
  public mutating func clearData() {self._data = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _polarShellMsgID: UInt32? = nil
  fileprivate var _data: String? = nil
}

public nonisolated struct Protocol_PbPftpPnsDHAttribute: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var type: Protocol_PbPftpPnsDHAttributeType {
    get {_type ?? .unknownAction}
    set {_type = newValue}
  }
  /// Returns true if `type` has been explicitly set.
  public var hasType: Bool {self._type != nil}
  /// Clears the value of `type`. Subsequent reads from it will return its default value.
  public mutating func clearType() {self._type = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _type: Protocol_PbPftpPnsDHAttributeType? = nil
}

public nonisolated struct Protocol_PbPftpPnsDHNotificationResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var notificationID: UInt32 {
    get {_notificationID ?? 0}
    set {_notificationID = newValue}
  }
  /// Returns true if `notificationID` has been explicitly set.
  public var hasNotificationID: Bool {self._notificationID != nil}
  /// Clears the value of `notificationID`. Subsequent reads from it will return its default value.
  public mutating func clearNotificationID() {self._notificationID = nil}

  public var attributes: [Protocol_PbPftpPnsDHAttribute] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _notificationID: UInt32? = nil
}

public nonisolated struct Protocol_PbPftpPnsState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var notificationsEnabled: Bool {
    get {_notificationsEnabled ?? false}
    set {_notificationsEnabled = newValue}
  }
  /// Returns true if `notificationsEnabled` has been explicitly set.
  public var hasNotificationsEnabled: Bool {self._notificationsEnabled != nil}
  /// Clears the value of `notificationsEnabled`. Subsequent reads from it will return its default value.
  public mutating func clearNotificationsEnabled() {self._notificationsEnabled = nil}

  public var previewEnabled: Bool {
    get {_previewEnabled ?? false}
    set {_previewEnabled = newValue}
  }
  /// Returns true if `previewEnabled` has been explicitly set.
  public var hasPreviewEnabled: Bool {self._previewEnabled != nil}
  /// Clears the value of `previewEnabled`. Subsequent reads from it will return its default value.
  public mutating func clearPreviewEnabled() {self._previewEnabled = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _notificationsEnabled: Bool? = nil
  fileprivate var _previewEnabled: Bool? = nil
}

public nonisolated struct Protocol_PbPftpStartGPSMeasurement: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var minimumInterval: UInt32 {
    get {_minimumInterval ?? 1000}
    set {_minimumInterval = newValue}
  }
  /// Returns true if `minimumInterval` has been explicitly set.
  public var hasMinimumInterval: Bool {self._minimumInterval != nil}
  /// Clears the value of `minimumInterval`. Subsequent reads from it will return its default value.
  public mutating func clearMinimumInterval() {self._minimumInterval = nil}

  public var accuracy: UInt32 {
    get {_accuracy ?? 2}
    set {_accuracy = newValue}
  }
  /// Returns true if `accuracy` has been explicitly set.
  public var hasAccuracy: Bool {self._accuracy != nil}
  /// Clears the value of `accuracy`. Subsequent reads from it will return its default value.
  public mutating func clearAccuracy() {self._accuracy = nil}

  public var latitude: Double {
    get {_latitude ?? 0}
    set {_latitude = newValue}
  }
  /// Returns true if `latitude` has been explicitly set.
  public var hasLatitude: Bool {self._latitude != nil}
  /// Clears the value of `latitude`. Subsequent reads from it will return its default value.
  public mutating func clearLatitude() {self._latitude = nil}

  public var longitude: Double {
    get {_longitude ?? 0}
    set {_longitude = newValue}
  }
  /// Returns true if `longitude` has been explicitly set.
  public var hasLongitude: Bool {self._longitude != nil}
  /// Clears the value of `longitude`. Subsequent reads from it will return its default value.
  public mutating func clearLongitude() {self._longitude = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _minimumInterval: UInt32? = nil
  fileprivate var _accuracy: UInt32? = nil
  fileprivate var _latitude: Double? = nil
  fileprivate var _longitude: Double? = nil
}

public nonisolated struct Protocol_PbPftpDHMediaControlRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var request: Protocol_MediaControlRequest {
    get {_request ?? .getMediaData}
    set {_request = newValue}
  }
  /// Returns true if `request` has been explicitly set.
  public var hasRequest: Bool {self._request != nil}
  /// Clears the value of `request`. Subsequent reads from it will return its default value.
  public mutating func clearRequest() {self._request = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _request: Protocol_MediaControlRequest? = nil
}

public nonisolated struct Protocol_PbPftpDHMediaControlCommand: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var command: Protocol_MediaControlCommand {
    get {_command ?? .play}
    set {_command = newValue}
  }
  /// Returns true if `command` has been explicitly set.
  public var hasCommand: Bool {self._command != nil}
  /// Clears the value of `command`. Subsequent reads from it will return its default value.
  public mutating func clearCommand() {self._command = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _command: Protocol_MediaControlCommand? = nil
}

public nonisolated struct Protocol_PbPftpDHMediaControlEnabled: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var enabled: Bool {
    get {_enabled ?? false}
    set {_enabled = newValue}
  }
  /// Returns true if `enabled` has been explicitly set.
  public var hasEnabled: Bool {self._enabled != nil}
  /// Clears the value of `enabled`. Subsequent reads from it will return its default value.
  public mutating func clearEnabled() {self._enabled = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _enabled: Bool? = nil
}

public nonisolated struct Protocol_PbPftpDHRestApiEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var event: [Data] = []

  /// If this field is missing or false, the payload is compressed
  public var uncompressed: Bool {
    get {_uncompressed ?? false}
    set {_uncompressed = newValue}
  }
  /// Returns true if `uncompressed` has been explicitly set.
  public var hasUncompressed: Bool {self._uncompressed != nil}
  /// Clears the value of `uncompressed`. Subsequent reads from it will return its default value.
  public mutating func clearUncompressed() {self._uncompressed = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _uncompressed: Bool? = nil
}

public nonisolated struct Protocol_PbPftpDHExerciseStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var exerciseState: Protocol_PbPftpDHExerciseStatus.PbExerciseState {
    get {_exerciseState ?? .exerciseStateOther}
    set {_exerciseState = newValue}
  }
  /// Returns true if `exerciseState` has been explicitly set.
  public var hasExerciseState: Bool {self._exerciseState != nil}
  /// Clears the value of `exerciseState`. Subsequent reads from it will return its default value.
  public mutating func clearExerciseState() {self._exerciseState = nil}

  public var exerciseType: Protocol_PbPftpDHExerciseStatus.PbExerciseType {
    get {_exerciseType ?? .exerciseTypeOther}
    set {_exerciseType = newValue}
  }
  /// Returns true if `exerciseType` has been explicitly set.
  public var hasExerciseType: Bool {self._exerciseType != nil}
  /// Clears the value of `exerciseType`. Subsequent reads from it will return its default value.
  public mutating func clearExerciseType() {self._exerciseType = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum PbExerciseState: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case exerciseStateOther = 0
    case exerciseStateRunning = 1
    case exerciseStatePaused = 2
    case exerciseStateOff = 3

    public init() {
      self = .exerciseStateOther
    }

  }

  public nonisolated enum PbExerciseType: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case exerciseTypeOther = 0
    case exerciseTypeTraining = 1
    case exerciseTypeNightlyRecharge = 2

    public init() {
      self = .exerciseTypeOther
    }

  }

  public init() {}

  fileprivate var _exerciseState: Protocol_PbPftpDHExerciseStatus.PbExerciseState? = nil
  fileprivate var _exerciseType: Protocol_PbPftpDHExerciseStatus.PbExerciseType? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protocol"

nonisolated extension Protocol_PbPFtpHostToDevNotification: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0START_SYNC\0\u{1}STOP_SYNC\0\u{1}RESET\0\u{2}\u{6}INITIALIZE_SESSION\0\u{1}TERMINATE_SESSION\0")
}

nonisolated extension Protocol_PbPFtpDevToHostNotification: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FILESYSTEM_MODIFIED\0\u{1}INTERNAL_TEST_EVENT\0\u{1}IDLING\0\u{1}BATTERY_STATUS\0\u{1}INACTIVITY_ALERT\0\u{1}TRAINING_SESSION_STATUS\0\u{2}\u{2}SYNC_REQUIRED\0\u{1}AUTOSYNC_STATUS\0\u{1}PNS_DH_NOTIFICATION_RESPONSE\0\u{1}PNS_SETTINGS\0\u{1}START_GPS_MEASUREMENT\0\u{1}STOP_GPS_MEASUREMENT\0\u{1}KEEP_BACKGROUND_ALIVE\0\u{1}POLAR_SHELL_DH_DATA\0\u{1}MEDIA_CONTROL_REQUEST_DH\0\u{1}MEDIA_CONTROL_COMMAND_DH\0\u{1}MEDIA_CONTROL_ENABLED\0\u{1}REST_API_EVENT\0\u{1}EXERCISE_STATUS\0")
}

nonisolated extension Protocol_Action: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0CREATED\0\u{1}UPDATED\0\u{1}REMOVED\0")
}

nonisolated extension Protocol_PbPFtpSyncTriggerSource: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0NO_SOURCE\0\u{1}USER\0\u{1}TIMED\0\u{1}FEATURE\0")
}

nonisolated extension Protocol_PbPftpPnsDHAttributeType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}UNKNOWN_ACTION\0\u{1}POSITIVE_ACTION\0\u{1}NEGATIVE_ACTION\0\u{1}CLEAR_ACTION\0\u{1}A_ACTION\0\u{1}B_ACTION\0\u{1}C_ACTION\0\u{1}D_ACTION\0")
}

nonisolated extension Protocol_MediaControlRequest: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}GET_MEDIA_DATA\0\u{1}GET_PLAYBACK_STATE\0")
}

nonisolated extension Protocol_MediaControlCommand: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}PLAY\0\u{1}PAUSE\0\u{1}TOGGLER_PLAY_PAUSE\0\u{1}NEXT\0\u{1}PREVIOUS\0\u{1}FAST_FORWARD\0\u{1}FAST_BACKWARD\0\u{1}VOLUME_UP\0\u{1}VOLUME_DOWN\0")
}

nonisolated extension Protocol_PbPFtpFactoryResetParams: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPFtpFactoryResetParams"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}sleep\0\u{3}do_factory_defaults\0\u{3}ota_fwupdate\0")

  public var isInitialized: Bool {
    if self._sleep == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._sleep) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self._doFactoryDefaults) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self._otaFwupdate) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._sleep {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._doFactoryDefaults {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._otaFwupdate {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPFtpFactoryResetParams, rhs: Protocol_PbPFtpFactoryResetParams) -> Bool {
    if lhs._sleep != rhs._sleep {return false}
    if lhs._doFactoryDefaults != rhs._doFactoryDefaults {return false}
    if lhs._otaFwupdate != rhs._otaFwupdate {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPFtpStopSyncParams: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPFtpStopSyncParams"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}completed\0")

  public var isInitialized: Bool {
    if self._completed == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._completed) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._completed {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPFtpStopSyncParams, rhs: Protocol_PbPFtpStopSyncParams) -> Bool {
    if lhs._completed != rhs._completed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPFtpFilesystemModifiedParams: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPFtpFilesystemModifiedParams"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}action\0\u{1}path\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._action) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._path) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._action {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._path {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPFtpFilesystemModifiedParams, rhs: Protocol_PbPFtpFilesystemModifiedParams) -> Bool {
    if lhs._action != rhs._action {return false}
    if lhs._path != rhs._path {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPFtpInactivityAlert: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPFtpInactivityAlert"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}countdown\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._countdown) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._countdown {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPFtpInactivityAlert, rhs: Protocol_PbPFtpInactivityAlert) -> Bool {
    if lhs._countdown != rhs._countdown {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPFtpTrainingSessionStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPFtpTrainingSessionStatus"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}inprogress\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._inprogress) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._inprogress {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPFtpTrainingSessionStatus, rhs: Protocol_PbPFtpTrainingSessionStatus) -> Bool {
    if lhs._inprogress != rhs._inprogress {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPFtpAutoSyncStatusParams: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPFtpAutoSyncStatusParams"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}succeeded\0\u{1}description\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._succeeded) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._description_p) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._succeeded {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._description_p {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPFtpAutoSyncStatusParams, rhs: Protocol_PbPFtpAutoSyncStatusParams) -> Bool {
    if lhs._succeeded != rhs._succeeded {return false}
    if lhs._description_p != rhs._description_p {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPFtpSyncTrigger: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPFtpSyncTrigger"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}source\0\u{3}feature_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._source) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._featureName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._source {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._featureName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPFtpSyncTrigger, rhs: Protocol_PbPFtpSyncTrigger) -> Bool {
    if lhs._source != rhs._source {return false}
    if lhs._featureName != rhs._featureName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPFtpSyncRequiredParams: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPFtpSyncRequiredParams"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}sync_triggers\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.syncTriggers) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.syncTriggers.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.syncTriggers, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPFtpSyncRequiredParams, rhs: Protocol_PbPFtpSyncRequiredParams) -> Bool {
    if lhs.syncTriggers != rhs.syncTriggers {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPFtpPolarShellMessageParams: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPFtpPolarShellMessageParams"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}polar_shell_msg_id\0\u{1}data\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._polarShellMsgID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._data) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._polarShellMsgID {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._data {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPFtpPolarShellMessageParams, rhs: Protocol_PbPFtpPolarShellMessageParams) -> Bool {
    if lhs._polarShellMsgID != rhs._polarShellMsgID {return false}
    if lhs._data != rhs._data {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPftpPnsDHAttribute: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPftpPnsDHAttribute"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._type) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._type {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPftpPnsDHAttribute, rhs: Protocol_PbPftpPnsDHAttribute) -> Bool {
    if lhs._type != rhs._type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPftpPnsDHNotificationResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPftpPnsDHNotificationResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}notification_id\0\u{1}attributes\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._notificationID) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.attributes) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._notificationID {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    if !self.attributes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.attributes, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPftpPnsDHNotificationResponse, rhs: Protocol_PbPftpPnsDHNotificationResponse) -> Bool {
    if lhs._notificationID != rhs._notificationID {return false}
    if lhs.attributes != rhs.attributes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPftpPnsState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPftpPnsState"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}notifications_enabled\0\u{3}preview_enabled\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._notificationsEnabled) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self._previewEnabled) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._notificationsEnabled {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._previewEnabled {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPftpPnsState, rhs: Protocol_PbPftpPnsState) -> Bool {
    if lhs._notificationsEnabled != rhs._notificationsEnabled {return false}
    if lhs._previewEnabled != rhs._previewEnabled {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPftpStartGPSMeasurement: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPftpStartGPSMeasurement"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}minimum_interval\0\u{1}accuracy\0\u{1}latitude\0\u{1}longitude\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._minimumInterval) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self._accuracy) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self._latitude) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self._longitude) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._minimumInterval {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._accuracy {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._latitude {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._longitude {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPftpStartGPSMeasurement, rhs: Protocol_PbPftpStartGPSMeasurement) -> Bool {
    if lhs._minimumInterval != rhs._minimumInterval {return false}
    if lhs._accuracy != rhs._accuracy {return false}
    if lhs._latitude != rhs._latitude {return false}
    if lhs._longitude != rhs._longitude {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPftpDHMediaControlRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPftpDHMediaControlRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}request\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._request) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._request {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPftpDHMediaControlRequest, rhs: Protocol_PbPftpDHMediaControlRequest) -> Bool {
    if lhs._request != rhs._request {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPftpDHMediaControlCommand: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPftpDHMediaControlCommand"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}command\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._command) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._command {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPftpDHMediaControlCommand, rhs: Protocol_PbPftpDHMediaControlCommand) -> Bool {
    if lhs._command != rhs._command {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPftpDHMediaControlEnabled: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPftpDHMediaControlEnabled"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}enabled\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._enabled) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._enabled {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPftpDHMediaControlEnabled, rhs: Protocol_PbPftpDHMediaControlEnabled) -> Bool {
    if lhs._enabled != rhs._enabled {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPftpDHRestApiEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPftpDHRestApiEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}event\0\u{1}uncompressed\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedBytesField(value: &self.event) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self._uncompressed) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.event.isEmpty {
      try visitor.visitRepeatedBytesField(value: self.event, fieldNumber: 1)
    }
    try { if let v = self._uncompressed {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPftpDHRestApiEvent, rhs: Protocol_PbPftpDHRestApiEvent) -> Bool {
    if lhs.event != rhs.event {return false}
    if lhs._uncompressed != rhs._uncompressed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPftpDHExerciseStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbPftpDHExerciseStatus"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}exercise_state\0\u{3}exercise_type\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._exerciseState) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self._exerciseType) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._exerciseState {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._exerciseType {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Protocol_PbPftpDHExerciseStatus, rhs: Protocol_PbPftpDHExerciseStatus) -> Bool {
    if lhs._exerciseState != rhs._exerciseState {return false}
    if lhs._exerciseType != rhs._exerciseType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Protocol_PbPftpDHExerciseStatus.PbExerciseState: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0EXERCISE_STATE_OTHER\0\u{1}EXERCISE_STATE_RUNNING\0\u{1}EXERCISE_STATE_PAUSED\0\u{1}EXERCISE_STATE_OFF\0")
}

nonisolated extension Protocol_PbPftpDHExerciseStatus.PbExerciseType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0EXERCISE_TYPE_OTHER\0\u{1}EXERCISE_TYPE_TRAINING\0\u{1}EXERCISE_TYPE_NIGHTLY_RECHARGE\0")
}
