// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: pftp_error.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

///
/// Error codes.
public nonisolated enum Protocol_PbPFtpError: Int, SwiftProtobuf.Enum, Swift.CaseIterable {

  /// Succeeding or no error 
  case operationSucceeded = 0
  case rebooting = 1
  case tryAgain = 2

  /// Host errors 
  case unidentifiedHostError = 100
  case invalidCommand = 101
  case invalidParameter = 102
  case noSuchFileOrDirectory = 103
  case directoryExists = 104
  case fileExists = 105
  case operationNotPermitted = 106
  case noSuchUser = 107
  case timeout = 108

  /// Device errors 
  case unidentifiedDeviceError = 200
  case notImplemented = 201
  case systemBusy = 202
  case invalidContent = 203
  case checksumFailure = 204
  case diskFull = 205
  case prerequisiteNotMet = 206
  case insufficientBuffer = 207
  case waitForIdling = 208

  /// 300-399 reserved for communication interface specific errors 
  case batteryTooLow = 209

  public init() {
    self = .operationSucceeded
  }

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

nonisolated extension Protocol_PbPFtpError: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0OPERATION_SUCCEEDED\0\u{1}REBOOTING\0\u{1}TRY_AGAIN\0\u{2}b\u{1}UNIDENTIFIED_HOST_ERROR\0\u{1}INVALID_COMMAND\0\u{1}INVALID_PARAMETER\0\u{1}NO_SUCH_FILE_OR_DIRECTORY\0\u{1}DIRECTORY_EXISTS\0\u{1}FILE_EXISTS\0\u{1}OPERATION_NOT_PERMITTED\0\u{1}NO_SUCH_USER\0\u{1}TIMEOUT\0\u{2}\\\u{1}UNIDENTIFIED_DEVICE_ERROR\0\u{1}NOT_IMPLEMENTED\0\u{1}SYSTEM_BUSY\0\u{1}INVALID_CONTENT\0\u{1}CHECKSUM_FAILURE\0\u{1}DISK_FULL\0\u{1}PREREQUISITE_NOT_MET\0\u{1}INSUFFICIENT_BUFFER\0\u{1}WAIT_FOR_IDLING\0\u{1}BATTERY_TOO_LOW\0")
}
