// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: temperature_measurement_period.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

///
///   Temperature measurement sample
public nonisolated struct Data_TemperatureMeasurementSample: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// recording time. Delta in milliseconds from beginning of the period.
  public var recordingTimeDeltaMilliseconds: UInt64 = 0

  /// Temperature in celsius.
  /// range [-40.0 - 125.0] C
  public var temperatureCelsius: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

///
///   Temperature measurement period
public nonisolated struct Data_TemperatureMeasurementPeriod: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var measurementType: TemperatureMeasurementType = .tmUnknown

  public var sourceDeviceID: String = String()

  /// Sensor location of source_device_id
  public var sensorLocation: SensorLocation = .slUnknown

  /// Temperature measurement samples.
  public var temperatureMeasurementSamples: [Data_TemperatureMeasurementSample] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "data"

nonisolated extension Data_TemperatureMeasurementSample: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TemperatureMeasurementSample"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}recording_time_delta_milliseconds\0\u{3}temperature_celsius\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.recordingTimeDeltaMilliseconds) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.temperatureCelsius) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.recordingTimeDeltaMilliseconds != 0 {
      try visitor.visitSingularUInt64Field(value: self.recordingTimeDeltaMilliseconds, fieldNumber: 1)
    }
    if self.temperatureCelsius.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.temperatureCelsius, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_TemperatureMeasurementSample, rhs: Data_TemperatureMeasurementSample) -> Bool {
    if lhs.recordingTimeDeltaMilliseconds != rhs.recordingTimeDeltaMilliseconds {return false}
    if lhs.temperatureCelsius != rhs.temperatureCelsius {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Data_TemperatureMeasurementPeriod: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TemperatureMeasurementPeriod"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}measurement_type\0\u{3}source_device_id\0\u{3}sensor_location\0\u{3}temperature_measurement_samples\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.measurementType) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.sourceDeviceID) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.sensorLocation) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.temperatureMeasurementSamples) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.measurementType != .tmUnknown {
      try visitor.visitSingularEnumField(value: self.measurementType, fieldNumber: 1)
    }
    if !self.sourceDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.sourceDeviceID, fieldNumber: 2)
    }
    if self.sensorLocation != .slUnknown {
      try visitor.visitSingularEnumField(value: self.sensorLocation, fieldNumber: 3)
    }
    if !self.temperatureMeasurementSamples.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.temperatureMeasurementSamples, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_TemperatureMeasurementPeriod, rhs: Data_TemperatureMeasurementPeriod) -> Bool {
    if lhs.measurementType != rhs.measurementType {return false}
    if lhs.sourceDeviceID != rhs.sourceDeviceID {return false}
    if lhs.sensorLocation != rhs.sensorLocation {return false}
    if lhs.temperatureMeasurementSamples != rhs.temperatureMeasurementSamples {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
