// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: types_proto3.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum TemperatureMeasurementType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case tmUnknown // = 0
  case tmSkinTemperature // = 1
  case tmCoreTemperature // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .tmUnknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .tmUnknown
    case 1: self = .tmSkinTemperature
    case 2: self = .tmCoreTemperature
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .tmUnknown: return 0
    case .tmSkinTemperature: return 1
    case .tmCoreTemperature: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [TemperatureMeasurementType] = [
    .tmUnknown,
    .tmSkinTemperature,
    .tmCoreTemperature,
  ]

}

public nonisolated enum SensorLocation: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case slUnknown // = 0

  /// Distal from core
  case slDistal // = 1

  /// Proximal from core
  case slProximal // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .slUnknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .slUnknown
    case 1: self = .slDistal
    case 2: self = .slProximal
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .slUnknown: return 0
    case .slDistal: return 1
    case .slProximal: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [SensorLocation] = [
    .slUnknown,
    .slDistal,
    .slProximal,
  ]

}

public nonisolated struct PbDateProto3: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var year: UInt32 = 0

  public var month: UInt32 = 0

  public var day: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

nonisolated extension TemperatureMeasurementType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0TM_UNKNOWN\0\u{1}TM_SKIN_TEMPERATURE\0\u{1}TM_CORE_TEMPERATURE\0")
}

nonisolated extension SensorLocation: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SL_UNKNOWN\0\u{1}SL_DISTAL\0\u{1}SL_PROXIMAL\0")
}

nonisolated extension PbDateProto3: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "PbDateProto3"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}year\0\u{1}month\0\u{1}day\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.year) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.month) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.day) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.year != 0 {
      try visitor.visitSingularUInt32Field(value: self.year, fieldNumber: 1)
    }
    if self.month != 0 {
      try visitor.visitSingularUInt32Field(value: self.month, fieldNumber: 2)
    }
    if self.day != 0 {
      try visitor.visitSingularUInt32Field(value: self.day, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: PbDateProto3, rhs: PbDateProto3) -> Bool {
    if lhs.year != rhs.year {return false}
    if lhs.month != rhs.month {return false}
    if lhs.day != rhs.day {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
