// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: user_physdata.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// PHYSDATA.BPB=PbUserPhysData

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct Data_PbUserBirthday: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// value should be in past.
  public var value: PbDate {
    get {_value ?? PbDate()}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  public var hasValue: Bool {self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  public mutating func clearValue() {self._value = nil}

  public var lastModified: PbSystemDateTime {
    get {_lastModified ?? PbSystemDateTime()}
    set {_lastModified = newValue}
  }
  /// Returns true if `lastModified` has been explicitly set.
  public var hasLastModified: Bool {self._lastModified != nil}
  /// Clears the value of `lastModified`. Subsequent reads from it will return its default value.
  public mutating func clearLastModified() {self._lastModified = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _value: PbDate? = nil
  fileprivate var _lastModified: PbSystemDateTime? = nil
}

public nonisolated struct Data_PbUserGender: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var value: Data_PbUserGender.Gender {
    get {_value ?? .male}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  public var hasValue: Bool {self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  public mutating func clearValue() {self._value = nil}

  public var lastModified: PbSystemDateTime {
    get {_lastModified ?? PbSystemDateTime()}
    set {_lastModified = newValue}
  }
  /// Returns true if `lastModified` has been explicitly set.
  public var hasLastModified: Bool {self._lastModified != nil}
  /// Clears the value of `lastModified`. Subsequent reads from it will return its default value.
  public mutating func clearLastModified() {self._lastModified = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum Gender: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case male = 1
    case female = 2

    public init() {
      self = .male
    }

  }

  public init() {}

  fileprivate var _value: Data_PbUserGender.Gender? = nil
  fileprivate var _lastModified: PbSystemDateTime? = nil
}

public nonisolated struct Data_PbUserHrAttribute: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// range [0-250] 1/min
  public var value: UInt32 {
    get {_value ?? 0}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  public var hasValue: Bool {self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  public mutating func clearValue() {self._value = nil}

  public var lastModified: PbSystemDateTime {
    get {_lastModified ?? PbSystemDateTime()}
    set {_lastModified = newValue}
  }
  /// Returns true if `lastModified` has been explicitly set.
  public var hasLastModified: Bool {self._lastModified != nil}
  /// Clears the value of `lastModified`. Subsequent reads from it will return its default value.
  public mutating func clearLastModified() {self._lastModified = nil}

  public var settingSource: Data_PbUserHrAttribute.HrSettingSource {
    get {_settingSource ?? .sourceDefault}
    set {_settingSource = newValue}
  }
  /// Returns true if `settingSource` has been explicitly set.
  public var hasSettingSource: Bool {self._settingSource != nil}
  /// Clears the value of `settingSource`. Subsequent reads from it will return its default value.
  public mutating func clearSettingSource() {self._settingSource = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum HrSettingSource: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case sourceDefault = 0
    case sourceAgeBased = 1
    case sourceUser = 2
    case sourceMeasured = 3
    case sourceKeep = 4

    public init() {
      self = .sourceDefault
    }

  }

  public init() {}

  fileprivate var _value: UInt32? = nil
  fileprivate var _lastModified: PbSystemDateTime? = nil
  fileprivate var _settingSource: Data_PbUserHrAttribute.HrSettingSource? = nil
}

public nonisolated struct Data_PbUserWeight: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// User weight (aka. User mass)
  /// range: [0.0-300.0] kg
  public var value: Float {
    get {_value ?? 0}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  public var hasValue: Bool {self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  public mutating func clearValue() {self._value = nil}

  public var lastModified: PbSystemDateTime {
    get {_lastModified ?? PbSystemDateTime()}
    set {_lastModified = newValue}
  }
  /// Returns true if `lastModified` has been explicitly set.
  public var hasLastModified: Bool {self._lastModified != nil}
  /// Clears the value of `lastModified`. Subsequent reads from it will return its default value.
  public mutating func clearLastModified() {self._lastModified = nil}

  public var settingSource: Data_PbUserWeight.WeightSettingSource {
    get {_settingSource ?? .sourceDefault}
    set {_settingSource = newValue}
  }
  /// Returns true if `settingSource` has been explicitly set.
  public var hasSettingSource: Bool {self._settingSource != nil}
  /// Clears the value of `settingSource`. Subsequent reads from it will return its default value.
  public mutating func clearSettingSource() {self._settingSource = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum WeightSettingSource: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case sourceDefault = 0
    case sourceUser = 2
    case sourceMeasured = 3

    public init() {
      self = .sourceDefault
    }

  }

  public init() {}

  fileprivate var _value: Float? = nil
  fileprivate var _lastModified: PbSystemDateTime? = nil
  fileprivate var _settingSource: Data_PbUserWeight.WeightSettingSource? = nil
}

public nonisolated struct Data_PbUserHeight: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// User Height
  /// range: [90.0-240.0] cm
  public var value: Float {
    get {_value ?? 0}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  public var hasValue: Bool {self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  public mutating func clearValue() {self._value = nil}

  public var lastModified: PbSystemDateTime {
    get {_lastModified ?? PbSystemDateTime()}
    set {_lastModified = newValue}
  }
  /// Returns true if `lastModified` has been explicitly set.
  public var hasLastModified: Bool {self._lastModified != nil}
  /// Clears the value of `lastModified`. Subsequent reads from it will return its default value.
  public mutating func clearLastModified() {self._lastModified = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _value: Float? = nil
  fileprivate var _lastModified: PbSystemDateTime? = nil
}

public nonisolated struct Data_PbUserVo2Max: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///
  /// Range: [10-95] ml/kg/min
  public var value: UInt32 {
    get {_value ?? 0}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  public var hasValue: Bool {self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  public mutating func clearValue() {self._value = nil}

  public var lastModified: PbSystemDateTime {
    get {_lastModified ?? PbSystemDateTime()}
    set {_lastModified = newValue}
  }
  /// Returns true if `lastModified` has been explicitly set.
  public var hasLastModified: Bool {self._lastModified != nil}
  /// Clears the value of `lastModified`. Subsequent reads from it will return its default value.
  public mutating func clearLastModified() {self._lastModified = nil}

  public var settingSource: Data_PbUserVo2Max.Vo2MaxSettingSource {
    get {_settingSource ?? .sourceDefault}
    set {_settingSource = newValue}
  }
  /// Returns true if `settingSource` has been explicitly set.
  public var hasSettingSource: Bool {self._settingSource != nil}
  /// Clears the value of `settingSource`. Subsequent reads from it will return its default value.
  public mutating func clearSettingSource() {self._settingSource = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum Vo2MaxSettingSource: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case sourceDefault = 0
    case sourceEstimate = 1
    case sourceUser = 2
    case sourceFitnesstest = 3

    public init() {
      self = .sourceDefault
    }

  }

  public init() {}

  fileprivate var _value: UInt32? = nil
  fileprivate var _lastModified: PbSystemDateTime? = nil
  fileprivate var _settingSource: Data_PbUserVo2Max.Vo2MaxSettingSource? = nil
}

public nonisolated struct Data_PbUserTrainingBackground: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var value: Data_PbUserTrainingBackground.TrainingBackground {
    get {_value ?? .occasional}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  public var hasValue: Bool {self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  public mutating func clearValue() {self._value = nil}

  public var lastModified: PbSystemDateTime {
    get {_lastModified ?? PbSystemDateTime()}
    set {_lastModified = newValue}
  }
  /// Returns true if `lastModified` has been explicitly set.
  public var hasLastModified: Bool {self._lastModified != nil}
  /// Clears the value of `lastModified`. Subsequent reads from it will return its default value.
  public mutating func clearLastModified() {self._lastModified = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum TrainingBackground: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case occasional = 10
    case regular = 20
    case frequent = 30
    case heavy = 40
    case semiPro = 50
    case pro = 60

    public init() {
      self = .occasional
    }

  }

  public init() {}

  fileprivate var _value: Data_PbUserTrainingBackground.TrainingBackground? = nil
  fileprivate var _lastModified: PbSystemDateTime? = nil
}

public nonisolated struct Data_PbUserTypicalDay: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var value: Data_PbUserTypicalDay.TypicalDay {
    get {_value ?? .mostlySitting}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  public var hasValue: Bool {self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  public mutating func clearValue() {self._value = nil}

  public var lastModified: PbSystemDateTime {
    get {_lastModified ?? PbSystemDateTime()}
    set {_lastModified = newValue}
  }
  /// Returns true if `lastModified` has been explicitly set.
  public var hasLastModified: Bool {self._lastModified != nil}
  /// Clears the value of `lastModified`. Subsequent reads from it will return its default value.
  public mutating func clearLastModified() {self._lastModified = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum TypicalDay: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case mostlySitting = 1
    case mostlyStanding = 2
    case mostlyMoving = 3

    public init() {
      self = .mostlySitting
    }

  }

  public init() {}

  fileprivate var _value: Data_PbUserTypicalDay.TypicalDay? = nil
  fileprivate var _lastModified: PbSystemDateTime? = nil
}

public nonisolated struct Data_PbSleepGoal: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The Sleep Goal of the user, in minutes. Can be null.
  public var sleepGoalMinutes: UInt32 {
    get {_sleepGoalMinutes ?? 0}
    set {_sleepGoalMinutes = newValue}
  }
  /// Returns true if `sleepGoalMinutes` has been explicitly set.
  public var hasSleepGoalMinutes: Bool {self._sleepGoalMinutes != nil}
  /// Clears the value of `sleepGoalMinutes`. Subsequent reads from it will return its default value.
  public mutating func clearSleepGoalMinutes() {self._sleepGoalMinutes = nil}

  public var lastModified: PbSystemDateTime {
    get {_lastModified ?? PbSystemDateTime()}
    set {_lastModified = newValue}
  }
  /// Returns true if `lastModified` has been explicitly set.
  public var hasLastModified: Bool {self._lastModified != nil}
  /// Clears the value of `lastModified`. Subsequent reads from it will return its default value.
  public mutating func clearLastModified() {self._lastModified = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _sleepGoalMinutes: UInt32? = nil
  fileprivate var _lastModified: PbSystemDateTime? = nil
}

public nonisolated struct Data_PbUserPhysData: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var birthday: Data_PbUserBirthday {
    get {_storage._birthday ?? Data_PbUserBirthday()}
    set {_uniqueStorage()._birthday = newValue}
  }
  /// Returns true if `birthday` has been explicitly set.
  public var hasBirthday: Bool {_storage._birthday != nil}
  /// Clears the value of `birthday`. Subsequent reads from it will return its default value.
  public mutating func clearBirthday() {_uniqueStorage()._birthday = nil}

  public var gender: Data_PbUserGender {
    get {_storage._gender ?? Data_PbUserGender()}
    set {_uniqueStorage()._gender = newValue}
  }
  /// Returns true if `gender` has been explicitly set.
  public var hasGender: Bool {_storage._gender != nil}
  /// Clears the value of `gender`. Subsequent reads from it will return its default value.
  public mutating func clearGender() {_uniqueStorage()._gender = nil}

  public var weight: Data_PbUserWeight {
    get {_storage._weight ?? Data_PbUserWeight()}
    set {_uniqueStorage()._weight = newValue}
  }
  /// Returns true if `weight` has been explicitly set.
  public var hasWeight: Bool {_storage._weight != nil}
  /// Clears the value of `weight`. Subsequent reads from it will return its default value.
  public mutating func clearWeight() {_uniqueStorage()._weight = nil}

  public var height: Data_PbUserHeight {
    get {_storage._height ?? Data_PbUserHeight()}
    set {_uniqueStorage()._height = newValue}
  }
  /// Returns true if `height` has been explicitly set.
  public var hasHeight: Bool {_storage._height != nil}
  /// Clears the value of `height`. Subsequent reads from it will return its default value.
  public mutating func clearHeight() {_uniqueStorage()._height = nil}

  public var maximumHeartrate: Data_PbUserHrAttribute {
    get {_storage._maximumHeartrate ?? Data_PbUserHrAttribute()}
    set {_uniqueStorage()._maximumHeartrate = newValue}
  }
  /// Returns true if `maximumHeartrate` has been explicitly set.
  public var hasMaximumHeartrate: Bool {_storage._maximumHeartrate != nil}
  /// Clears the value of `maximumHeartrate`. Subsequent reads from it will return its default value.
  public mutating func clearMaximumHeartrate() {_uniqueStorage()._maximumHeartrate = nil}

  public var restingHeartrate: Data_PbUserHrAttribute {
    get {_storage._restingHeartrate ?? Data_PbUserHrAttribute()}
    set {_uniqueStorage()._restingHeartrate = newValue}
  }
  /// Returns true if `restingHeartrate` has been explicitly set.
  public var hasRestingHeartrate: Bool {_storage._restingHeartrate != nil}
  /// Clears the value of `restingHeartrate`. Subsequent reads from it will return its default value.
  public mutating func clearRestingHeartrate() {_uniqueStorage()._restingHeartrate = nil}

  public var vo2Max: Data_PbUserVo2Max {
    get {_storage._vo2Max ?? Data_PbUserVo2Max()}
    set {_uniqueStorage()._vo2Max = newValue}
  }
  /// Returns true if `vo2Max` has been explicitly set.
  public var hasVo2Max: Bool {_storage._vo2Max != nil}
  /// Clears the value of `vo2Max`. Subsequent reads from it will return its default value.
  public mutating func clearVo2Max() {_uniqueStorage()._vo2Max = nil}

  public var trainingBackground: Data_PbUserTrainingBackground {
    get {_storage._trainingBackground ?? Data_PbUserTrainingBackground()}
    set {_uniqueStorage()._trainingBackground = newValue}
  }
  /// Returns true if `trainingBackground` has been explicitly set.
  public var hasTrainingBackground: Bool {_storage._trainingBackground != nil}
  /// Clears the value of `trainingBackground`. Subsequent reads from it will return its default value.
  public mutating func clearTrainingBackground() {_uniqueStorage()._trainingBackground = nil}

  public var typicalDay: Data_PbUserTypicalDay {
    get {_storage._typicalDay ?? Data_PbUserTypicalDay()}
    set {_uniqueStorage()._typicalDay = newValue}
  }
  /// Returns true if `typicalDay` has been explicitly set.
  public var hasTypicalDay: Bool {_storage._typicalDay != nil}
  /// Clears the value of `typicalDay`. Subsequent reads from it will return its default value.
  public mutating func clearTypicalDay() {_uniqueStorage()._typicalDay = nil}

  /// The Sleep Goal of the user
  public var sleepGoal: Data_PbSleepGoal {
    get {_storage._sleepGoal ?? Data_PbSleepGoal()}
    set {_uniqueStorage()._sleepGoal = newValue}
  }
  /// Returns true if `sleepGoal` has been explicitly set.
  public var hasSleepGoal: Bool {_storage._sleepGoal != nil}
  /// Clears the value of `sleepGoal`. Subsequent reads from it will return its default value.
  public mutating func clearSleepGoal() {_uniqueStorage()._sleepGoal = nil}

  ///
  /// Timestamps for the whole component: these are updated
  /// if any of the component fields are updated.
  public var lastModified: PbSystemDateTime {
    get {_storage._lastModified ?? PbSystemDateTime()}
    set {_uniqueStorage()._lastModified = newValue}
  }
  /// Returns true if `lastModified` has been explicitly set.
  public var hasLastModified: Bool {_storage._lastModified != nil}
  /// Clears the value of `lastModified`. Subsequent reads from it will return its default value.
  public mutating func clearLastModified() {_uniqueStorage()._lastModified = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "data"

nonisolated extension Data_PbUserBirthday: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbUserBirthday"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0\u{3}last_modified\0")

  public var isInitialized: Bool {
    if self._value == nil {return false}
    if self._lastModified == nil {return false}
    if let v = self._value, !v.isInitialized {return false}
    if let v = self._lastModified, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._value) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._lastModified) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._value {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._lastModified {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbUserBirthday, rhs: Data_PbUserBirthday) -> Bool {
    if lhs._value != rhs._value {return false}
    if lhs._lastModified != rhs._lastModified {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Data_PbUserGender: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbUserGender"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0\u{3}last_modified\0")

  public var isInitialized: Bool {
    if self._value == nil {return false}
    if self._lastModified == nil {return false}
    if let v = self._lastModified, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._value) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._lastModified) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._value {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._lastModified {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbUserGender, rhs: Data_PbUserGender) -> Bool {
    if lhs._value != rhs._value {return false}
    if lhs._lastModified != rhs._lastModified {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Data_PbUserGender.Gender: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}MALE\0\u{1}FEMALE\0")
}

nonisolated extension Data_PbUserHrAttribute: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbUserHrAttribute"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0\u{3}last_modified\0\u{3}setting_source\0")

  public var isInitialized: Bool {
    if self._value == nil {return false}
    if self._lastModified == nil {return false}
    if let v = self._lastModified, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._value) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._lastModified) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self._settingSource) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._value {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._lastModified {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._settingSource {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbUserHrAttribute, rhs: Data_PbUserHrAttribute) -> Bool {
    if lhs._value != rhs._value {return false}
    if lhs._lastModified != rhs._lastModified {return false}
    if lhs._settingSource != rhs._settingSource {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Data_PbUserHrAttribute.HrSettingSource: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SOURCE_DEFAULT\0\u{1}SOURCE_AGE_BASED\0\u{1}SOURCE_USER\0\u{1}SOURCE_MEASURED\0\u{1}SOURCE_KEEP\0")
}

nonisolated extension Data_PbUserWeight: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbUserWeight"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0\u{3}last_modified\0\u{3}setting_source\0")

  public var isInitialized: Bool {
    if self._value == nil {return false}
    if self._lastModified == nil {return false}
    if let v = self._lastModified, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self._value) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._lastModified) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self._settingSource) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._value {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._lastModified {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._settingSource {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbUserWeight, rhs: Data_PbUserWeight) -> Bool {
    if lhs._value != rhs._value {return false}
    if lhs._lastModified != rhs._lastModified {return false}
    if lhs._settingSource != rhs._settingSource {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Data_PbUserWeight.WeightSettingSource: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SOURCE_DEFAULT\0\u{2}\u{2}SOURCE_USER\0\u{1}SOURCE_MEASURED\0")
}

nonisolated extension Data_PbUserHeight: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbUserHeight"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0\u{3}last_modified\0")

  public var isInitialized: Bool {
    if self._value == nil {return false}
    if self._lastModified == nil {return false}
    if let v = self._lastModified, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self._value) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._lastModified) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._value {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._lastModified {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbUserHeight, rhs: Data_PbUserHeight) -> Bool {
    if lhs._value != rhs._value {return false}
    if lhs._lastModified != rhs._lastModified {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Data_PbUserVo2Max: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbUserVo2Max"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0\u{3}last_modified\0\u{3}setting_source\0")

  public var isInitialized: Bool {
    if self._value == nil {return false}
    if self._lastModified == nil {return false}
    if let v = self._lastModified, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._value) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._lastModified) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self._settingSource) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._value {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._lastModified {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._settingSource {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbUserVo2Max, rhs: Data_PbUserVo2Max) -> Bool {
    if lhs._value != rhs._value {return false}
    if lhs._lastModified != rhs._lastModified {return false}
    if lhs._settingSource != rhs._settingSource {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Data_PbUserVo2Max.Vo2MaxSettingSource: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SOURCE_DEFAULT\0\u{1}SOURCE_ESTIMATE\0\u{1}SOURCE_USER\0\u{1}SOURCE_FITNESSTEST\0")
}

nonisolated extension Data_PbUserTrainingBackground: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbUserTrainingBackground"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0\u{3}last_modified\0")

  public var isInitialized: Bool {
    if self._value == nil {return false}
    if self._lastModified == nil {return false}
    if let v = self._lastModified, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._value) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._lastModified) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._value {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._lastModified {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbUserTrainingBackground, rhs: Data_PbUserTrainingBackground) -> Bool {
    if lhs._value != rhs._value {return false}
    if lhs._lastModified != rhs._lastModified {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Data_PbUserTrainingBackground.TrainingBackground: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{a}OCCASIONAL\0\u{2}\u{a}REGULAR\0\u{2}\u{a}FREQUENT\0\u{2}\u{a}HEAVY\0\u{2}\u{a}SEMI_PRO\0\u{2}\u{a}PRO\0")
}

nonisolated extension Data_PbUserTypicalDay: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbUserTypicalDay"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0\u{3}last_modified\0")

  public var isInitialized: Bool {
    if self._value == nil {return false}
    if self._lastModified == nil {return false}
    if let v = self._lastModified, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._value) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._lastModified) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._value {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._lastModified {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbUserTypicalDay, rhs: Data_PbUserTypicalDay) -> Bool {
    if lhs._value != rhs._value {return false}
    if lhs._lastModified != rhs._lastModified {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Data_PbUserTypicalDay.TypicalDay: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}MOSTLY_SITTING\0\u{1}MOSTLY_STANDING\0\u{1}MOSTLY_MOVING\0")
}

nonisolated extension Data_PbSleepGoal: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbSleepGoal"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}sleep_goal_minutes\0\u{3}last_modified\0")

  public var isInitialized: Bool {
    if let v = self._lastModified, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._sleepGoalMinutes) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._lastModified) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._sleepGoalMinutes {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._lastModified {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbSleepGoal, rhs: Data_PbSleepGoal) -> Bool {
    if lhs._sleepGoalMinutes != rhs._sleepGoalMinutes {return false}
    if lhs._lastModified != rhs._lastModified {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Data_PbUserPhysData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PbUserPhysData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}birthday\0\u{1}gender\0\u{1}weight\0\u{1}height\0\u{3}maximum_heartrate\0\u{3}resting_heartrate\0\u{2}\u{4}vo2max\0\u{3}training_background\0\u{3}typical_day\0\u{4}\u{5}sleep_goal\0\u{4}S\u{1}last_modified\0")

  fileprivate class _StorageClass {
    var _birthday: Data_PbUserBirthday? = nil
    var _gender: Data_PbUserGender? = nil
    var _weight: Data_PbUserWeight? = nil
    var _height: Data_PbUserHeight? = nil
    var _maximumHeartrate: Data_PbUserHrAttribute? = nil
    var _restingHeartrate: Data_PbUserHrAttribute? = nil
    var _vo2Max: Data_PbUserVo2Max? = nil
    var _trainingBackground: Data_PbUserTrainingBackground? = nil
    var _typicalDay: Data_PbUserTypicalDay? = nil
    var _sleepGoal: Data_PbSleepGoal? = nil
    var _lastModified: PbSystemDateTime? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _birthday = source._birthday
      _gender = source._gender
      _weight = source._weight
      _height = source._height
      _maximumHeartrate = source._maximumHeartrate
      _restingHeartrate = source._restingHeartrate
      _vo2Max = source._vo2Max
      _trainingBackground = source._trainingBackground
      _typicalDay = source._typicalDay
      _sleepGoal = source._sleepGoal
      _lastModified = source._lastModified
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public var isInitialized: Bool {
    return withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._birthday == nil {return false}
      if _storage._gender == nil {return false}
      if let v = _storage._birthday, !v.isInitialized {return false}
      if let v = _storage._gender, !v.isInitialized {return false}
      if let v = _storage._weight, !v.isInitialized {return false}
      if let v = _storage._height, !v.isInitialized {return false}
      if let v = _storage._maximumHeartrate, !v.isInitialized {return false}
      if let v = _storage._restingHeartrate, !v.isInitialized {return false}
      if let v = _storage._vo2Max, !v.isInitialized {return false}
      if let v = _storage._trainingBackground, !v.isInitialized {return false}
      if let v = _storage._typicalDay, !v.isInitialized {return false}
      if let v = _storage._sleepGoal, !v.isInitialized {return false}
      if let v = _storage._lastModified, !v.isInitialized {return false}
      return true
    }
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._birthday) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._gender) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._weight) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._height) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._maximumHeartrate) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._restingHeartrate) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._vo2Max) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._trainingBackground) }()
        case 12: try { try decoder.decodeSingularMessageField(value: &_storage._typicalDay) }()
        case 17: try { try decoder.decodeSingularMessageField(value: &_storage._sleepGoal) }()
        case 100: try { try decoder.decodeSingularMessageField(value: &_storage._lastModified) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._birthday {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._gender {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._weight {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._height {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._maximumHeartrate {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._restingHeartrate {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._vo2Max {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._trainingBackground {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._typicalDay {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._sleepGoal {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 17)
      } }()
      try { if let v = _storage._lastModified {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 100)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Data_PbUserPhysData, rhs: Data_PbUserPhysData) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._birthday != rhs_storage._birthday {return false}
        if _storage._gender != rhs_storage._gender {return false}
        if _storage._weight != rhs_storage._weight {return false}
        if _storage._height != rhs_storage._height {return false}
        if _storage._maximumHeartrate != rhs_storage._maximumHeartrate {return false}
        if _storage._restingHeartrate != rhs_storage._restingHeartrate {return false}
        if _storage._vo2Max != rhs_storage._vo2Max {return false}
        if _storage._trainingBackground != rhs_storage._trainingBackground {return false}
        if _storage._typicalDay != rhs_storage._typicalDay {return false}
        if _storage._sleepGoal != rhs_storage._sleepGoal {return false}
        if _storage._lastModified != rhs_storage._lastModified {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
